// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module network_top_network_top_Pipeline_load_weight3_matrix_inner_loop111 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        add_ln225,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] add_ln225;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239_ap_vld;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln223_fu_442_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg   [6:0] c_28_reg_1106;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] c_28_reg_1106_pp0_iter1_reg;
reg   [6:0] c_28_reg_1106_pp0_iter2_reg;
reg   [6:0] c_28_reg_1106_pp0_iter3_reg;
reg   [6:0] c_28_reg_1106_pp0_iter4_reg;
reg   [6:0] c_28_reg_1106_pp0_iter5_reg;
reg   [6:0] c_28_reg_1106_pp0_iter6_reg;
reg   [6:0] c_28_reg_1106_pp0_iter7_reg;
reg   [6:0] c_28_reg_1106_pp0_iter8_reg;
reg   [63:0] gmem_addr_reg_1114;
wire  signed [63:0] sext_ln225_fu_552_p1;
wire   [21:0] trunc_ln225_28_fu_600_p1;
reg   [6:0] phi_urem801_fu_394;
wire   [6:0] select_ln223_fu_577_p3;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_phi_urem801_load_1;
reg   [6:0] ap_sig_allocacmp_phi_urem801_load;
reg   [14:0] phi_mul799_fu_398;
wire   [14:0] next_mul800_fu_460_p2;
reg   [14:0] ap_sig_allocacmp_phi_mul799_load;
reg   [6:0] c_fu_402;
wire   [6:0] add_ln223_fu_448_p2;
reg   [6:0] ap_sig_allocacmp_c_28;
wire   [2:0] tmp_fu_466_p4;
wire   [2:0] mul_ln225_fu_480_p0;
wire   [10:0] mul_ln225_fu_480_p1;
wire   [11:0] mul_ln225_fu_480_p2;
wire   [6:0] trunc_ln225_fu_486_p1;
wire   [4:0] tmp_s_fu_496_p4;
wire   [6:0] or_ln225_fu_490_p2;
wire   [11:0] or_ln225_s_fu_506_p3;
wire   [12:0] zext_ln225_fu_514_p1;
wire   [12:0] add_ln225_35_fu_518_p2;
wire   [14:0] shl_ln225_s_fu_524_p3;
wire   [63:0] zext_ln225_21_fu_532_p1;
wire   [63:0] add_ln225_36_fu_536_p2;
wire   [61:0] trunc_ln225_s_fu_542_p4;
wire   [6:0] add_ln223_18_fu_565_p2;
wire   [0:0] icmp_ln223_18_fu_571_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] mul_ln225_fu_480_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_done_reg = 1'b0;
end

network_top_mul_3ns_11ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
mul_3ns_11ns_12_1_1_U9381(
    .din0(mul_ln225_fu_480_p0),
    .din1(mul_ln225_fu_480_p1),
    .dout(mul_ln225_fu_480_p2)
);

network_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            c_fu_402 <= add_ln223_fu_448_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_402 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            phi_mul799_fu_398 <= next_mul800_fu_460_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul799_fu_398 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            phi_urem801_fu_394 <= select_ln223_fu_577_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem801_fu_394 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        c_28_reg_1106 <= ap_sig_allocacmp_c_28;
        c_28_reg_1106_pp0_iter1_reg <= c_28_reg_1106;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        c_28_reg_1106_pp0_iter2_reg <= c_28_reg_1106_pp0_iter1_reg;
        c_28_reg_1106_pp0_iter3_reg <= c_28_reg_1106_pp0_iter2_reg;
        c_28_reg_1106_pp0_iter4_reg <= c_28_reg_1106_pp0_iter3_reg;
        c_28_reg_1106_pp0_iter5_reg <= c_28_reg_1106_pp0_iter4_reg;
        c_28_reg_1106_pp0_iter6_reg <= c_28_reg_1106_pp0_iter5_reg;
        c_28_reg_1106_pp0_iter7_reg <= c_28_reg_1106_pp0_iter6_reg;
        c_28_reg_1106_pp0_iter8_reg <= c_28_reg_1106_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln223_fu_442_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_addr_reg_1114 <= sext_ln225_fu_552_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln223_fu_442_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_c_28 = 7'd0;
    end else begin
        ap_sig_allocacmp_c_28 = c_fu_402;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul799_load = 15'd0;
    end else begin
        ap_sig_allocacmp_phi_mul799_load = phi_mul799_fu_398;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem801_load = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem801_load = phi_urem801_fu_394;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem801_load_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem801_load_1 = phi_urem801_fu_394;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd70) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd71) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & ((c_28_reg_1106_pp0_iter8_reg == 7'd79) | ((c_28_reg_1106_pp0_iter8_reg == 7'd80) | ((c_28_reg_1106_pp0_iter8_reg == 7'd81) | ((c_28_reg_1106_pp0_iter8_reg == 7'd82) | ((c_28_reg_1106_pp0_iter8_reg == 7'd83) | ((c_28_reg_1106_pp0_iter8_reg == 7'd84) | ((c_28_reg_1106_pp0_iter8_reg == 7'd85) | ((c_28_reg_1106_pp0_iter8_reg == 7'd86) | ((c_28_reg_1106_pp0_iter8_reg == 7'd87) | ((c_28_reg_1106_pp0_iter8_reg == 7'd88) | ((c_28_reg_1106_pp0_iter8_reg == 7'd89) | ((c_28_reg_1106_pp0_iter8_reg == 7'd90) | ((c_28_reg_1106_pp0_iter8_reg == 7'd91) | ((c_28_reg_1106_pp0_iter8_reg == 7'd92) | ((c_28_reg_1106_pp0_iter8_reg == 7'd93) | ((c_28_reg_1106_pp0_iter8_reg == 7'd94) | ((c_28_reg_1106_pp0_iter8_reg == 7'd95) | ((c_28_reg_1106_pp0_iter8_reg == 7'd96) | ((c_28_reg_1106_pp0_iter8_reg == 7'd97) | ((c_28_reg_1106_pp0_iter8_reg == 7'd98) | ((c_28_reg_1106_pp0_iter8_reg == 7'd99) | ((c_28_reg_1106_pp0_iter8_reg == 7'd100) | ((c_28_reg_1106_pp0_iter8_reg 
    == 7'd101) | ((c_28_reg_1106_pp0_iter8_reg == 7'd102) | ((c_28_reg_1106_pp0_iter8_reg == 7'd103) | ((c_28_reg_1106_pp0_iter8_reg == 7'd104) | ((c_28_reg_1106_pp0_iter8_reg == 7'd105) | ((c_28_reg_1106_pp0_iter8_reg == 7'd106) | ((c_28_reg_1106_pp0_iter8_reg == 7'd107) | ((c_28_reg_1106_pp0_iter8_reg == 7'd108) | ((c_28_reg_1106_pp0_iter8_reg == 7'd109) | ((c_28_reg_1106_pp0_iter8_reg == 7'd110) | ((c_28_reg_1106_pp0_iter8_reg == 7'd111) | ((c_28_reg_1106_pp0_iter8_reg == 7'd112) | ((c_28_reg_1106_pp0_iter8_reg == 7'd113) | ((c_28_reg_1106_pp0_iter8_reg == 7'd114) | ((c_28_reg_1106_pp0_iter8_reg == 7'd115) | ((c_28_reg_1106_pp0_iter8_reg == 7'd116) | ((c_28_reg_1106_pp0_iter8_reg == 7'd117) | ((c_28_reg_1106_pp0_iter8_reg == 7'd118) | ((c_28_reg_1106_pp0_iter8_reg == 7'd119) | ((c_28_reg_1106_pp0_iter8_reg == 7'd120) | ((c_28_reg_1106_pp0_iter8_reg == 7'd121) | ((c_28_reg_1106_pp0_iter8_reg == 7'd122) | ((c_28_reg_1106_pp0_iter8_reg == 7'd123) | ((c_28_reg_1106_pp0_iter8_reg == 7'd124) | ((c_28_reg_1106_pp0_iter8_reg 
    == 7'd125) | ((c_28_reg_1106_pp0_iter8_reg == 7'd126) | (c_28_reg_1106_pp0_iter8_reg == 7'd127))))))))))))))))))))))))))))))))))))))))))))))))))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd78) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd69) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd68) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd67) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd66) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd65) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd64) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd63) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd62) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd61) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd72) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd60) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd77) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd59) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd58) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd57) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd16) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd17) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd18) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd19) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd73) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd20) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd21) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd22) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd23) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd24) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd25) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd26) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd27) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd28) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd29) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd74) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd30) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd31) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd32) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd33) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd34) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd35) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd36) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd37) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd38) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd39) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd75) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd40) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd41) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd42) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd43) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd44) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd45) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd46) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd47) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd48) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd49) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd76) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd50) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd51) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd52) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd53) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd54) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd55) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd56) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_28_reg_1106_pp0_iter8_reg == 7'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln223_18_fu_565_p2 = (ap_sig_allocacmp_phi_urem801_load + 7'd1);

assign add_ln223_fu_448_p2 = (ap_sig_allocacmp_c_28 + 7'd1);

assign add_ln225_35_fu_518_p2 = (zext_ln225_fu_514_p1 + 13'd660);

assign add_ln225_36_fu_536_p2 = (add_ln225 + zext_ln225_21_fu_532_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln223_18_fu_571_p2 = ((add_ln223_18_fu_565_p2 < 7'd20) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_442_p2 = ((ap_sig_allocacmp_c_28 == 7'd80) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = gmem_addr_reg_1114;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign mul_ln225_fu_480_p0 = mul_ln225_fu_480_p00;

assign mul_ln225_fu_480_p00 = tmp_fu_466_p4;

assign mul_ln225_fu_480_p1 = 12'd800;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_10 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_21 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_239 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_240 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_241 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_252 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_263 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_274 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_285 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_296 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_307 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_318 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_32 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_329 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_33 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_34 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_340 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_35 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_351 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_352 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_36 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_363 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_37 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_374 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_38 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_39 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_40 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_41 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_42 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_43 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_44 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_45 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_46 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_47 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_48 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_49 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_50 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_51 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_52 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_53 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_54 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_55 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_56 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_57 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_58 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_59 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_60 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_61 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_62 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_63 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_64 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_65 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_66 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_67 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_68 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_69 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_70 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_71 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_72 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_73 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_74 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_75 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_76 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_77 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_78 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_79 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_80 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_81 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_82 = trunc_ln225_28_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_93 = trunc_ln225_28_fu_600_p1;

assign next_mul800_fu_460_p2 = (ap_sig_allocacmp_phi_mul799_load + 15'd205);

assign or_ln225_fu_490_p2 = (trunc_ln225_fu_486_p1 | ap_sig_allocacmp_phi_urem801_load_1);

assign or_ln225_s_fu_506_p3 = {{tmp_s_fu_496_p4}, {or_ln225_fu_490_p2}};

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18620 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18621 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18622 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18623 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18624 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18625 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18626 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18627 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18628 = trunc_ln225_28_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_18629 = trunc_ln225_28_fu_600_p1;

assign select_ln223_fu_577_p3 = ((icmp_ln223_18_fu_571_p2[0:0] == 1'b1) ? add_ln223_18_fu_565_p2 : 7'd0);

assign sext_ln225_fu_552_p1 = $signed(trunc_ln225_s_fu_542_p4);

assign shl_ln225_s_fu_524_p3 = {{add_ln225_35_fu_518_p2}, {2'd0}};

assign tmp_fu_466_p4 = {{ap_sig_allocacmp_phi_mul799_load[14:12]}};

assign tmp_s_fu_496_p4 = {{mul_ln225_fu_480_p2[11:7]}};

assign trunc_ln225_28_fu_600_p1 = m_axi_gmem_RDATA[21:0];

assign trunc_ln225_fu_486_p1 = mul_ln225_fu_480_p2[6:0];

assign trunc_ln225_s_fu_542_p4 = {{add_ln225_36_fu_536_p2[63:2]}};

assign zext_ln225_21_fu_532_p1 = shl_ln225_s_fu_524_p3;

assign zext_ln225_fu_514_p1 = or_ln225_s_fu_506_p3;

endmodule //network_top_network_top_Pipeline_load_weight3_matrix_inner_loop111
