// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module network_top_network_top_Pipeline_load_weight3_matrix_inner_loop91 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        add_ln225,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868_ap_vld,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869,
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309_ap_vld,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308,
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] add_ln225;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868_ap_vld;
output  [21:0] p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869;
output   p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309_ap_vld;
output  [21:0] network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308;
output   network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308_ap_vld;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868_ap_vld;
reg p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309_ap_vld;
reg network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln223_fu_442_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg   [6:0] c_9_reg_1106;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] c_9_reg_1106_pp0_iter1_reg;
reg   [6:0] c_9_reg_1106_pp0_iter2_reg;
reg   [6:0] c_9_reg_1106_pp0_iter3_reg;
reg   [6:0] c_9_reg_1106_pp0_iter4_reg;
reg   [6:0] c_9_reg_1106_pp0_iter5_reg;
reg   [6:0] c_9_reg_1106_pp0_iter6_reg;
reg   [6:0] c_9_reg_1106_pp0_iter7_reg;
reg   [6:0] c_9_reg_1106_pp0_iter8_reg;
reg   [63:0] gmem_addr_reg_1114;
wire  signed [63:0] sext_ln225_fu_552_p1;
wire   [21:0] trunc_ln225_9_fu_600_p1;
reg   [6:0] phi_urem701_fu_394;
wire   [6:0] select_ln223_fu_577_p3;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_phi_urem701_load_1;
reg   [6:0] ap_sig_allocacmp_phi_urem701_load;
reg   [14:0] phi_mul699_fu_398;
wire   [14:0] next_mul700_fu_460_p2;
reg   [14:0] ap_sig_allocacmp_phi_mul699_load;
reg   [6:0] c_fu_402;
wire   [6:0] add_ln223_fu_448_p2;
reg   [6:0] ap_sig_allocacmp_c_9;
wire   [2:0] tmp_fu_466_p4;
wire   [2:0] mul_ln225_fu_480_p0;
wire   [10:0] mul_ln225_fu_480_p1;
wire   [11:0] mul_ln225_fu_480_p2;
wire   [6:0] trunc_ln225_fu_486_p1;
wire   [4:0] tmp_s_fu_496_p4;
wire   [6:0] or_ln225_fu_490_p2;
wire   [11:0] or_ln225_s_fu_506_p3;
wire   [12:0] zext_ln225_fu_514_p1;
wire   [12:0] add_ln225_17_fu_518_p2;
wire   [14:0] shl_ln225_s_fu_524_p3;
wire   [63:0] zext_ln225_9_fu_532_p1;
wire   [63:0] add_ln225_18_fu_536_p2;
wire   [61:0] trunc_ln225_s_fu_542_p4;
wire   [6:0] add_ln223_9_fu_565_p2;
wire   [0:0] icmp_ln223_9_fu_571_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] mul_ln225_fu_480_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_done_reg = 1'b0;
end

network_top_mul_3ns_11ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
mul_3ns_11ns_12_1_1_U7721(
    .din0(mul_ln225_fu_480_p0),
    .din1(mul_ln225_fu_480_p1),
    .dout(mul_ln225_fu_480_p2)
);

network_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            c_fu_402 <= add_ln223_fu_448_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_402 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            phi_mul699_fu_398 <= next_mul700_fu_460_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul699_fu_398 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln223_fu_442_p2 == 1'd0))) begin
            phi_urem701_fu_394 <= select_ln223_fu_577_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem701_fu_394 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        c_9_reg_1106 <= ap_sig_allocacmp_c_9;
        c_9_reg_1106_pp0_iter1_reg <= c_9_reg_1106;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        c_9_reg_1106_pp0_iter2_reg <= c_9_reg_1106_pp0_iter1_reg;
        c_9_reg_1106_pp0_iter3_reg <= c_9_reg_1106_pp0_iter2_reg;
        c_9_reg_1106_pp0_iter4_reg <= c_9_reg_1106_pp0_iter3_reg;
        c_9_reg_1106_pp0_iter5_reg <= c_9_reg_1106_pp0_iter4_reg;
        c_9_reg_1106_pp0_iter6_reg <= c_9_reg_1106_pp0_iter5_reg;
        c_9_reg_1106_pp0_iter7_reg <= c_9_reg_1106_pp0_iter6_reg;
        c_9_reg_1106_pp0_iter8_reg <= c_9_reg_1106_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln223_fu_442_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_addr_reg_1114 <= sext_ln225_fu_552_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln223_fu_442_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_c_9 = 7'd0;
    end else begin
        ap_sig_allocacmp_c_9 = c_fu_402;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul699_load = 15'd0;
    end else begin
        ap_sig_allocacmp_phi_mul699_load = phi_mul699_fu_398;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem701_load = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem701_load = phi_urem701_fu_394;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem701_load_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem701_load_1 = phi_urem701_fu_394;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & ((c_9_reg_1106_pp0_iter8_reg == 7'd79) | ((c_9_reg_1106_pp0_iter8_reg == 7'd80) | ((c_9_reg_1106_pp0_iter8_reg == 7'd81) | ((c_9_reg_1106_pp0_iter8_reg == 7'd82) | ((c_9_reg_1106_pp0_iter8_reg == 7'd83) | ((c_9_reg_1106_pp0_iter8_reg == 7'd84) | ((c_9_reg_1106_pp0_iter8_reg == 7'd85) | ((c_9_reg_1106_pp0_iter8_reg == 7'd86) | ((c_9_reg_1106_pp0_iter8_reg == 7'd87) | ((c_9_reg_1106_pp0_iter8_reg == 7'd88) | ((c_9_reg_1106_pp0_iter8_reg == 7'd89) | ((c_9_reg_1106_pp0_iter8_reg == 7'd90) | ((c_9_reg_1106_pp0_iter8_reg == 7'd91) | ((c_9_reg_1106_pp0_iter8_reg == 7'd92) | ((c_9_reg_1106_pp0_iter8_reg == 7'd93) | ((c_9_reg_1106_pp0_iter8_reg == 7'd94) | ((c_9_reg_1106_pp0_iter8_reg == 7'd95) | ((c_9_reg_1106_pp0_iter8_reg == 7'd96) | ((c_9_reg_1106_pp0_iter8_reg == 7'd97) | ((c_9_reg_1106_pp0_iter8_reg == 7'd98) | ((c_9_reg_1106_pp0_iter8_reg == 7'd99) | ((c_9_reg_1106_pp0_iter8_reg == 7'd100) | ((c_9_reg_1106_pp0_iter8_reg == 7'd101) | ((c_9_reg_1106_pp0_iter8_reg 
    == 7'd102) | ((c_9_reg_1106_pp0_iter8_reg == 7'd103) | ((c_9_reg_1106_pp0_iter8_reg == 7'd104) | ((c_9_reg_1106_pp0_iter8_reg == 7'd105) | ((c_9_reg_1106_pp0_iter8_reg == 7'd106) | ((c_9_reg_1106_pp0_iter8_reg == 7'd107) | ((c_9_reg_1106_pp0_iter8_reg == 7'd108) | ((c_9_reg_1106_pp0_iter8_reg == 7'd109) | ((c_9_reg_1106_pp0_iter8_reg == 7'd110) | ((c_9_reg_1106_pp0_iter8_reg == 7'd111) | ((c_9_reg_1106_pp0_iter8_reg == 7'd112) | ((c_9_reg_1106_pp0_iter8_reg == 7'd113) | ((c_9_reg_1106_pp0_iter8_reg == 7'd114) | ((c_9_reg_1106_pp0_iter8_reg == 7'd115) | ((c_9_reg_1106_pp0_iter8_reg == 7'd116) | ((c_9_reg_1106_pp0_iter8_reg == 7'd117) | ((c_9_reg_1106_pp0_iter8_reg == 7'd118) | ((c_9_reg_1106_pp0_iter8_reg == 7'd119) | ((c_9_reg_1106_pp0_iter8_reg == 7'd120) | ((c_9_reg_1106_pp0_iter8_reg == 7'd121) | ((c_9_reg_1106_pp0_iter8_reg == 7'd122) | ((c_9_reg_1106_pp0_iter8_reg == 7'd123) | ((c_9_reg_1106_pp0_iter8_reg == 7'd124) | ((c_9_reg_1106_pp0_iter8_reg == 7'd125) | ((c_9_reg_1106_pp0_iter8_reg == 7'd126) | (c_9_reg_1106_pp0_iter8_reg 
    == 7'd127))))))))))))))))))))))))))))))))))))))))))))))))))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd78) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd77) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd76) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd75) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd74) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd73) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd72) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd71) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd70) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd69) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd68) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd67) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd66) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd65) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd64) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd63) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd62) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd61) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd60) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd59) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd58) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd57) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd56) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd55) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd54) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd53) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd52) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd51) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd50) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd49) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd48) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd47) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd46) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd45) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd44) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd43) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd42) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd41) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd40) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd39) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd38) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd37) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd36) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd35) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd34) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd33) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd32) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd31) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd30) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd29) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd28) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd27) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd26) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd25) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd24) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd23) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd22) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd21) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd20) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd19) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd18) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd17) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd16) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (c_9_reg_1106_pp0_iter8_reg == 7'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln223_9_fu_565_p2 = (ap_sig_allocacmp_phi_urem701_load + 7'd1);

assign add_ln223_fu_448_p2 = (ap_sig_allocacmp_c_9 + 7'd1);

assign add_ln225_17_fu_518_p2 = (zext_ln225_fu_514_p1 + 13'd260);

assign add_ln225_18_fu_536_p2 = (add_ln225 + zext_ln225_9_fu_532_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln223_9_fu_571_p2 = ((add_ln223_9_fu_565_p2 < 7'd20) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_442_p2 = ((ap_sig_allocacmp_c_9 == 7'd80) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = gmem_addr_reg_1114;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign mul_ln225_fu_480_p0 = mul_ln225_fu_480_p00;

assign mul_ln225_fu_480_p00 = tmp_fu_466_p4;

assign mul_ln225_fu_480_p1 = 12'd800;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_308 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_309 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_310 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_311 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_312 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_313 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_314 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_315 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_316 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_317 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_319 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_320 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_321 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_322 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_323 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_324 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_325 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_326 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_327 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_328 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_330 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_331 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_332 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_333 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_334 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_335 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_336 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_337 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_338 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_339 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_341 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_342 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_343 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_344 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_345 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_346 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_347 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_348 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_349 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_350 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_353 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_354 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_355 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_356 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_357 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_358 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_359 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_360 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_361 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_362 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_364 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_365 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_366 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_367 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_368 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_369 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_370 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_371 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_372 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_373 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_375 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_376 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_377 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_378 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_94 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_95 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_96 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_97 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_98 = trunc_ln225_9_fu_600_p1;

assign network_top_params_struct_ap_fixed_ap_fixed_ap_int_ap_int_32_weights3_99 = trunc_ln225_9_fu_600_p1;

assign next_mul700_fu_460_p2 = (ap_sig_allocacmp_phi_mul699_load + 15'd205);

assign or_ln225_fu_490_p2 = (trunc_ln225_fu_486_p1 | ap_sig_allocacmp_phi_urem701_load_1);

assign or_ln225_s_fu_506_p3 = {{tmp_s_fu_496_p4}, {or_ln225_fu_490_p2}};

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16860 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16861 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16862 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16863 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16864 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16865 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16866 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16867 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16868 = trunc_ln225_9_fu_600_p1;

assign p_ZZ11network_topP13params_structP8ap_fixedILi22ELi17EL9ap_q_mode0EL9ap_o_mode0EL_16869 = trunc_ln225_9_fu_600_p1;

assign select_ln223_fu_577_p3 = ((icmp_ln223_9_fu_571_p2[0:0] == 1'b1) ? add_ln223_9_fu_565_p2 : 7'd0);

assign sext_ln225_fu_552_p1 = $signed(trunc_ln225_s_fu_542_p4);

assign shl_ln225_s_fu_524_p3 = {{add_ln225_17_fu_518_p2}, {2'd0}};

assign tmp_fu_466_p4 = {{ap_sig_allocacmp_phi_mul699_load[14:12]}};

assign tmp_s_fu_496_p4 = {{mul_ln225_fu_480_p2[11:7]}};

assign trunc_ln225_9_fu_600_p1 = m_axi_gmem_RDATA[21:0];

assign trunc_ln225_fu_486_p1 = mul_ln225_fu_480_p2[6:0];

assign trunc_ln225_s_fu_542_p4 = {{add_ln225_18_fu_536_p2[63:2]}};

assign zext_ln225_9_fu_532_p1 = shl_ln225_s_fu_524_p3;

assign zext_ln225_fu_514_p1 = or_ln225_s_fu_506_p3;

endmodule //network_top_network_top_Pipeline_load_weight3_matrix_inner_loop91
