// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        weights_0_0_val288,
        weights_0_1_val320,
        weights_0_2_val352,
        weights_0_3_val384,
        weights_0_4_val416,
        weights_0_5_val448,
        weights_0_6_val480,
        weights_0_7_val512,
        weights_0_8_val544,
        weights_0_9_val577,
        weights_0_10_val609,
        weights_0_11_val641,
        weights_0_12_val673,
        weights_0_13_val705,
        weights_0_14_val737,
        weights_0_15_val769,
        weights_0_16_val801,
        weights_0_17_val833,
        weights_0_18_val865,
        weights_0_19_val897,
        weights_0_20_val929,
        weights_0_21_val961,
        weights_0_22_val993,
        weights_0_23_val1025,
        weights_0_24_val1057,
        weights_0_25_val1089,
        weights_0_26_val1121,
        weights_0_27_val1153,
        weights_0_28_val1185,
        weights_0_29_val1217,
        weights_0_30_val1249,
        weights_0_31_val1281,
        weights_1_0_val1313,
        weights_1_1_val1345,
        weights_1_2_val1377,
        weights_1_3_val1409,
        weights_1_4_val1441,
        weights_1_5_val1473,
        weights_1_6_val1505,
        weights_1_7_val1537,
        weights_1_8_val1569,
        weights_1_9_val1601,
        weights_1_10_val1633,
        weights_1_11_val1665,
        weights_1_12_val1698,
        weights_1_13_val1730,
        weights_1_14_val1762,
        weights_1_15_val1794,
        weights_1_16_val1826,
        weights_1_17_val1858,
        weights_1_18_val1890,
        weights_1_19_val1922,
        weights_1_20_val1954,
        weights_1_21_val1986,
        weights_1_22_val2018,
        weights_1_23_val2050,
        weights_1_24_val2082,
        weights_1_25_val2114,
        weights_1_26_val2146,
        weights_1_27_val2178,
        weights_1_28_val2210,
        weights_1_29_val2243,
        weights_1_30_val2275,
        weights_1_31_val2307,
        weights_2_0_val2339,
        weights_2_1_val2371,
        weights_2_2_val2403,
        weights_2_3_val2435,
        weights_2_4_val2467,
        weights_2_5_val2499,
        weights_2_6_val2531,
        weights_2_7_val2563,
        weights_2_8_val2595,
        weights_2_9_val2627,
        weights_2_10_val2659,
        weights_2_11_val2691,
        weights_2_12_val2723,
        weights_2_13_val2755,
        weights_2_14_val2788,
        weights_2_15_val2820,
        weights_2_16_val2852,
        weights_2_17_val2884,
        weights_2_18_val2916,
        weights_2_19_val2948,
        weights_2_20_val2980,
        weights_2_21_val3012,
        weights_2_22_val3044,
        weights_2_23_val3076,
        weights_2_24_val3108,
        weights_2_25_val3140,
        weights_2_26_val3172,
        weights_2_27_val3204,
        weights_2_28_val3236,
        weights_2_29_val3268,
        weights_2_30_val3300,
        weights_2_31_val3333,
        weights_3_0_val3365,
        weights_3_1_val3397,
        weights_3_2_val3429,
        weights_3_3_val3461,
        weights_3_4_val3493,
        weights_3_5_val3525,
        weights_3_6_val3557,
        weights_3_7_val3589,
        weights_3_8_val3621,
        weights_3_9_val3653,
        weights_3_10_val3685,
        weights_3_11_val3717,
        weights_3_12_val3749,
        weights_3_13_val3781,
        weights_3_14_val3813,
        weights_3_15_val3845,
        weights_3_16_val3878,
        weights_3_17_val3910,
        weights_3_18_val3942,
        weights_3_19_val3974,
        weights_3_20_val4006,
        weights_3_21_val4038,
        weights_3_22_val4070,
        weights_3_23_val4102,
        weights_3_24_val4134,
        weights_3_25_val4166,
        weights_3_26_val4198,
        weights_3_27_val4230,
        weights_3_28_val4262,
        weights_3_29_val4294,
        weights_3_30_val4326,
        weights_3_31_val4358,
        weights_4_0_val4390,
        weights_4_1_val4423,
        weights_4_2_val4455,
        weights_4_3_val4487,
        weights_4_4_val4519,
        weights_4_5_val4551,
        weights_4_6_val4583,
        weights_4_7_val4615,
        weights_4_8_val4647,
        weights_4_9_val4679,
        weights_4_10_val4711,
        weights_4_11_val4743,
        weights_4_12_val4775,
        weights_4_13_val4807,
        weights_4_14_val4839,
        weights_4_15_val4871,
        weights_4_16_val4903,
        weights_4_17_val4935,
        weights_4_18_val4968,
        weights_4_19_val5000,
        weights_4_20_val5032,
        weights_4_21_val5064,
        weights_4_22_val5096,
        weights_4_23_val5128,
        weights_4_24_val5160,
        weights_4_25_val5192,
        weights_4_26_val5224,
        weights_4_27_val5256,
        weights_4_28_val5288,
        weights_4_29_val5320,
        weights_4_30_val5352,
        weights_4_31_val5384,
        weights_5_0_val5416,
        weights_5_1_val5448,
        weights_5_2_val5480,
        weights_5_3_val5513,
        weights_5_4_val5545,
        weights_5_5_val5577,
        weights_5_6_val5609,
        weights_5_7_val5641,
        weights_5_8_val5673,
        weights_5_9_val5705,
        weights_5_10_val5737,
        weights_5_11_val5769,
        weights_5_12_val5801,
        weights_5_13_val5833,
        weights_5_14_val5865,
        weights_5_15_val5897,
        weights_5_16_val5929,
        weights_5_17_val5961,
        weights_5_18_val5993,
        weights_5_19_val6025,
        weights_5_20_val6058,
        weights_5_21_val6090,
        weights_5_22_val6122,
        weights_5_23_val6154,
        weights_5_24_val6186,
        weights_5_25_val6218,
        weights_5_26_val6250,
        weights_5_27_val6282,
        weights_5_28_val6314,
        weights_5_29_val6346,
        weights_5_30_val6378,
        weights_5_31_val6410,
        weights_6_0_val6442,
        weights_6_1_val6474,
        weights_6_2_val6506,
        weights_6_3_val6538,
        weights_6_4_val6570,
        weights_6_5_val6603,
        weights_6_6_val6635,
        weights_6_7_val6667,
        weights_6_8_val6699,
        weights_6_9_val6731,
        weights_6_10_val6763,
        weights_6_11_val6795,
        weights_6_12_val6827,
        weights_6_13_val6859,
        weights_6_14_val6891,
        weights_6_15_val6923,
        weights_6_16_val6955,
        weights_6_17_val6987,
        weights_6_18_val7019,
        weights_6_19_val7051,
        weights_6_20_val7083,
        weights_6_21_val7115,
        weights_6_22_val7148,
        weights_6_23_val7180,
        weights_6_24_val7212,
        weights_6_25_val7244,
        weights_6_26_val7276,
        weights_6_27_val7308,
        weights_6_28_val7340,
        weights_6_29_val7372,
        weights_6_30_val7404,
        weights_6_31_val7436,
        weights_7_0_val7468,
        weights_7_1_val7500,
        weights_7_2_val7532,
        weights_7_3_val7564,
        weights_7_4_val7596,
        weights_7_5_val7628,
        weights_7_6_val7660,
        weights_7_7_val7693,
        weights_7_8_val7725,
        weights_7_9_val7757,
        weights_7_10_val7789,
        weights_7_11_val7821,
        weights_7_12_val7853,
        weights_7_13_val7885,
        weights_7_14_val7917,
        weights_7_15_val7949,
        weights_7_16_val7981,
        weights_7_17_val8013,
        weights_7_18_val8045,
        weights_7_19_val8077,
        weights_7_20_val8109,
        weights_7_21_val8141,
        weights_7_22_val8173,
        weights_7_23_val8205,
        weights_7_24_val8238,
        weights_7_25_val8270,
        weights_7_26_val8302,
        weights_7_27_val8334,
        weights_7_28_val8366,
        weights_7_29_val8398,
        weights_7_30_val8430,
        weights_7_31_val8462,
        weights_8_0_val8494,
        weights_8_1_val8526,
        weights_8_2_val8558,
        weights_8_3_val8590,
        weights_8_4_val8622,
        weights_8_5_val8654,
        weights_8_6_val8686,
        weights_8_7_val8718,
        weights_8_8_val8750,
        weights_8_9_val8783,
        weights_8_10_val8815,
        weights_8_11_val8847,
        weights_8_12_val8879,
        weights_8_13_val8911,
        weights_8_14_val8943,
        weights_8_15_val8975,
        weights_8_16_val9007,
        weights_8_17_val9039,
        weights_8_18_val9071,
        weights_8_19_val9103,
        weights_8_20_val9135,
        weights_8_21_val9167,
        weights_8_22_val9199,
        weights_8_23_val9231,
        weights_8_24_val9263,
        weights_8_25_val9295,
        weights_8_26_val9327,
        weights_8_27_val9359,
        weights_8_28_val9391,
        weights_8_29_val9423,
        weights_8_30_val9455,
        weights_8_31_val9487,
        weights_9_0_val9519,
        weights_9_1_val9551,
        weights_9_2_val9583,
        weights_9_3_val9615,
        weights_9_4_val9647,
        weights_9_5_val9679,
        weights_9_6_val9711,
        weights_9_7_val9743,
        weights_9_8_val9775,
        weights_9_9_val9807,
        weights_9_10_val9839,
        weights_9_11_val9871,
        weights_9_12_val9903,
        weights_9_13_val9935,
        weights_9_14_val9967,
        weights_9_15_val9999,
        weights_9_16_val10031,
        weights_9_17_val10063,
        weights_9_18_val10095,
        weights_9_19_val10127,
        weights_9_20_val10159,
        weights_9_21_val10191,
        weights_9_22_val10223,
        weights_9_23_val10255,
        weights_9_24_val10287,
        weights_9_25_val10319,
        weights_9_26_val10351,
        weights_9_27_val10383,
        weights_9_28_val10415,
        weights_9_29_val10447,
        weights_9_30_val10479,
        weights_9_31_val10511,
        weights_10_0_val10543,
        weights_10_1_val10575,
        weights_10_2_val10607,
        weights_10_3_val10639,
        weights_10_4_val10671,
        weights_10_5_val10703,
        weights_10_6_val10735,
        weights_10_7_val10767,
        weights_10_8_val10799,
        weights_10_9_val10831,
        weights_10_10_val10863,
        weights_10_11_val10895,
        weights_10_12_val10927,
        weights_10_13_val10959,
        weights_10_14_val10991,
        weights_10_15_val11023,
        weights_10_16_val11055,
        weights_10_17_val11087,
        weights_10_18_val11119,
        weights_10_19_val11151,
        weights_10_20_val11183,
        weights_10_21_val11215,
        weights_10_22_val11247,
        weights_10_23_val11279,
        weights_10_24_val11311,
        weights_10_25_val11343,
        weights_10_26_val11375,
        weights_10_27_val11407,
        weights_10_28_val11439,
        weights_10_29_val11471,
        weights_10_30_val11503,
        weights_10_31_val11535,
        weights_11_0_val11567,
        weights_11_1_val11599,
        weights_11_2_val11631,
        weights_11_3_val11663,
        weights_11_4_val11695,
        weights_11_5_val11727,
        weights_11_6_val11759,
        weights_11_7_val11791,
        weights_11_8_val11823,
        weights_11_9_val11855,
        weights_11_10_val11887,
        weights_11_11_val11919,
        weights_11_12_val11951,
        weights_11_13_val11983,
        weights_11_14_val12015,
        weights_11_15_val12047,
        weights_11_16_val12079,
        weights_11_17_val12111,
        weights_11_18_val12143,
        weights_11_19_val12175,
        weights_11_20_val12207,
        weights_11_21_val12239,
        weights_11_22_val12271,
        weights_11_23_val12303,
        weights_11_24_val12335,
        weights_11_25_val12367,
        weights_11_26_val12399,
        weights_11_27_val12431,
        weights_11_28_val12463,
        weights_11_29_val12495,
        weights_11_30_val12527,
        weights_11_31_val12559,
        weights_12_0_val12591,
        weights_12_1_val12623,
        weights_12_2_val12655,
        weights_12_3_val12687,
        weights_12_4_val12719,
        weights_12_5_val12751,
        weights_12_6_val12783,
        weights_12_7_val12815,
        weights_12_8_val12847,
        weights_12_9_val12879,
        weights_12_10_val12911,
        weights_12_11_val12943,
        weights_12_12_val12975,
        weights_12_13_val13007,
        weights_12_14_val13039,
        weights_12_15_val13071,
        weights_12_16_val13103,
        weights_12_17_val13135,
        weights_12_18_val13167,
        weights_12_19_val13199,
        weights_12_20_val13231,
        weights_12_21_val13263,
        weights_12_22_val13295,
        weights_12_23_val13327,
        weights_12_24_val13359,
        weights_12_25_val13391,
        weights_12_26_val13423,
        weights_12_27_val13455,
        weights_12_28_val13487,
        weights_12_29_val13519,
        weights_12_30_val13551,
        weights_12_31_val13583,
        weights_13_0_val13615,
        weights_13_1_val13647,
        weights_13_2_val13679,
        weights_13_3_val13712,
        weights_13_4_val13744,
        weights_13_5_val13776,
        weights_13_6_val13808,
        weights_13_7_val13840,
        weights_13_8_val13872,
        weights_13_9_val13904,
        weights_13_10_val13936,
        weights_13_11_val13968,
        weights_13_12_val14000,
        weights_13_13_val14032,
        weights_13_14_val14064,
        weights_13_15_val14096,
        weights_13_16_val14128,
        weights_13_17_val14160,
        weights_13_18_val14192,
        weights_13_19_val14224,
        weights_13_20_val14257,
        weights_13_21_val14289,
        weights_13_22_val14321,
        weights_13_23_val14353,
        weights_13_24_val14385,
        weights_13_25_val14417,
        weights_13_26_val14449,
        weights_13_27_val14481,
        weights_13_28_val14513,
        weights_13_29_val14545,
        weights_13_30_val14577,
        weights_13_31_val14609,
        weights_14_0_val14641,
        weights_14_1_val14673,
        weights_14_2_val14705,
        weights_14_3_val14737,
        weights_14_4_val14769,
        weights_14_5_val14802,
        weights_14_6_val14834,
        weights_14_7_val14866,
        weights_14_8_val14898,
        weights_14_9_val14930,
        weights_14_10_val14962,
        weights_14_11_val14994,
        weights_14_12_val15026,
        weights_14_13_val15058,
        weights_14_14_val15090,
        weights_14_15_val15122,
        weights_14_16_val15154,
        weights_14_17_val15186,
        weights_14_18_val15218,
        weights_14_19_val15250,
        weights_14_20_val15282,
        weights_14_21_val15314,
        weights_14_22_val15346,
        weights_14_23_val15378,
        weights_14_24_val15410,
        weights_14_25_val15442,
        weights_14_26_val15474,
        weights_14_27_val15506,
        weights_14_28_val15538,
        weights_14_29_val15570,
        weights_14_30_val15602,
        weights_14_31_val15634,
        weights_15_0_val15666,
        weights_15_1_val15698,
        weights_15_2_val15730,
        weights_15_3_val15762,
        weights_15_4_val15794,
        weights_15_5_val15826,
        weights_15_6_val15858,
        weights_15_7_val15890,
        weights_15_8_val15922,
        weights_15_9_val15954,
        weights_15_10_val15986,
        weights_15_11_val16018,
        weights_15_12_val16050,
        weights_15_13_val16082,
        weights_15_14_val16114,
        weights_15_15_val16146,
        weights_15_16_val16178,
        weights_15_17_val16210,
        weights_15_18_val16242,
        weights_15_19_val16274,
        weights_15_20_val16306,
        weights_15_21_val16338,
        weights_15_22_val16370,
        weights_15_23_val16402,
        weights_15_24_val16434,
        weights_15_25_val16466,
        weights_15_26_val16498,
        weights_15_27_val16530,
        weights_15_28_val16562,
        weights_15_29_val16594,
        weights_15_30_val16626,
        weights_15_31_val16658,
        input_0_val32,
        input_1_val64,
        input_2_val96,
        input_3_val128,
        input_4_val160,
        input_5_val192,
        input_6_val224,
        input_7_val256,
        hidden_state_0_read,
        hidden_state_1_read,
        hidden_state_2_read,
        hidden_state_3_read,
        hidden_state_4_read,
        hidden_state_5_read,
        hidden_state_6_read,
        hidden_state_7_read,
        output_vectors_0_0_out,
        output_vectors_0_0_out_ap_vld,
        output_vectors_1_0_out,
        output_vectors_1_0_out_ap_vld,
        output_vectors_2_0_out,
        output_vectors_2_0_out_ap_vld,
        output_vectors_3_0_out,
        output_vectors_3_0_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] p_read16;
input  [11:0] p_read17;
input  [11:0] p_read18;
input  [11:0] p_read19;
input  [11:0] weights_0_0_val288;
input  [11:0] weights_0_1_val320;
input  [11:0] weights_0_2_val352;
input  [11:0] weights_0_3_val384;
input  [11:0] weights_0_4_val416;
input  [11:0] weights_0_5_val448;
input  [11:0] weights_0_6_val480;
input  [11:0] weights_0_7_val512;
input  [11:0] weights_0_8_val544;
input  [11:0] weights_0_9_val577;
input  [11:0] weights_0_10_val609;
input  [11:0] weights_0_11_val641;
input  [11:0] weights_0_12_val673;
input  [11:0] weights_0_13_val705;
input  [11:0] weights_0_14_val737;
input  [11:0] weights_0_15_val769;
input  [11:0] weights_0_16_val801;
input  [11:0] weights_0_17_val833;
input  [11:0] weights_0_18_val865;
input  [11:0] weights_0_19_val897;
input  [11:0] weights_0_20_val929;
input  [11:0] weights_0_21_val961;
input  [11:0] weights_0_22_val993;
input  [11:0] weights_0_23_val1025;
input  [11:0] weights_0_24_val1057;
input  [11:0] weights_0_25_val1089;
input  [11:0] weights_0_26_val1121;
input  [11:0] weights_0_27_val1153;
input  [11:0] weights_0_28_val1185;
input  [11:0] weights_0_29_val1217;
input  [11:0] weights_0_30_val1249;
input  [11:0] weights_0_31_val1281;
input  [11:0] weights_1_0_val1313;
input  [11:0] weights_1_1_val1345;
input  [11:0] weights_1_2_val1377;
input  [11:0] weights_1_3_val1409;
input  [11:0] weights_1_4_val1441;
input  [11:0] weights_1_5_val1473;
input  [11:0] weights_1_6_val1505;
input  [11:0] weights_1_7_val1537;
input  [11:0] weights_1_8_val1569;
input  [11:0] weights_1_9_val1601;
input  [11:0] weights_1_10_val1633;
input  [11:0] weights_1_11_val1665;
input  [11:0] weights_1_12_val1698;
input  [11:0] weights_1_13_val1730;
input  [11:0] weights_1_14_val1762;
input  [11:0] weights_1_15_val1794;
input  [11:0] weights_1_16_val1826;
input  [11:0] weights_1_17_val1858;
input  [11:0] weights_1_18_val1890;
input  [11:0] weights_1_19_val1922;
input  [11:0] weights_1_20_val1954;
input  [11:0] weights_1_21_val1986;
input  [11:0] weights_1_22_val2018;
input  [11:0] weights_1_23_val2050;
input  [11:0] weights_1_24_val2082;
input  [11:0] weights_1_25_val2114;
input  [11:0] weights_1_26_val2146;
input  [11:0] weights_1_27_val2178;
input  [11:0] weights_1_28_val2210;
input  [11:0] weights_1_29_val2243;
input  [11:0] weights_1_30_val2275;
input  [11:0] weights_1_31_val2307;
input  [11:0] weights_2_0_val2339;
input  [11:0] weights_2_1_val2371;
input  [11:0] weights_2_2_val2403;
input  [11:0] weights_2_3_val2435;
input  [11:0] weights_2_4_val2467;
input  [11:0] weights_2_5_val2499;
input  [11:0] weights_2_6_val2531;
input  [11:0] weights_2_7_val2563;
input  [11:0] weights_2_8_val2595;
input  [11:0] weights_2_9_val2627;
input  [11:0] weights_2_10_val2659;
input  [11:0] weights_2_11_val2691;
input  [11:0] weights_2_12_val2723;
input  [11:0] weights_2_13_val2755;
input  [11:0] weights_2_14_val2788;
input  [11:0] weights_2_15_val2820;
input  [11:0] weights_2_16_val2852;
input  [11:0] weights_2_17_val2884;
input  [11:0] weights_2_18_val2916;
input  [11:0] weights_2_19_val2948;
input  [11:0] weights_2_20_val2980;
input  [11:0] weights_2_21_val3012;
input  [11:0] weights_2_22_val3044;
input  [11:0] weights_2_23_val3076;
input  [11:0] weights_2_24_val3108;
input  [11:0] weights_2_25_val3140;
input  [11:0] weights_2_26_val3172;
input  [11:0] weights_2_27_val3204;
input  [11:0] weights_2_28_val3236;
input  [11:0] weights_2_29_val3268;
input  [11:0] weights_2_30_val3300;
input  [11:0] weights_2_31_val3333;
input  [11:0] weights_3_0_val3365;
input  [11:0] weights_3_1_val3397;
input  [11:0] weights_3_2_val3429;
input  [11:0] weights_3_3_val3461;
input  [11:0] weights_3_4_val3493;
input  [11:0] weights_3_5_val3525;
input  [11:0] weights_3_6_val3557;
input  [11:0] weights_3_7_val3589;
input  [11:0] weights_3_8_val3621;
input  [11:0] weights_3_9_val3653;
input  [11:0] weights_3_10_val3685;
input  [11:0] weights_3_11_val3717;
input  [11:0] weights_3_12_val3749;
input  [11:0] weights_3_13_val3781;
input  [11:0] weights_3_14_val3813;
input  [11:0] weights_3_15_val3845;
input  [11:0] weights_3_16_val3878;
input  [11:0] weights_3_17_val3910;
input  [11:0] weights_3_18_val3942;
input  [11:0] weights_3_19_val3974;
input  [11:0] weights_3_20_val4006;
input  [11:0] weights_3_21_val4038;
input  [11:0] weights_3_22_val4070;
input  [11:0] weights_3_23_val4102;
input  [11:0] weights_3_24_val4134;
input  [11:0] weights_3_25_val4166;
input  [11:0] weights_3_26_val4198;
input  [11:0] weights_3_27_val4230;
input  [11:0] weights_3_28_val4262;
input  [11:0] weights_3_29_val4294;
input  [11:0] weights_3_30_val4326;
input  [11:0] weights_3_31_val4358;
input  [11:0] weights_4_0_val4390;
input  [11:0] weights_4_1_val4423;
input  [11:0] weights_4_2_val4455;
input  [11:0] weights_4_3_val4487;
input  [11:0] weights_4_4_val4519;
input  [11:0] weights_4_5_val4551;
input  [11:0] weights_4_6_val4583;
input  [11:0] weights_4_7_val4615;
input  [11:0] weights_4_8_val4647;
input  [11:0] weights_4_9_val4679;
input  [11:0] weights_4_10_val4711;
input  [11:0] weights_4_11_val4743;
input  [11:0] weights_4_12_val4775;
input  [11:0] weights_4_13_val4807;
input  [11:0] weights_4_14_val4839;
input  [11:0] weights_4_15_val4871;
input  [11:0] weights_4_16_val4903;
input  [11:0] weights_4_17_val4935;
input  [11:0] weights_4_18_val4968;
input  [11:0] weights_4_19_val5000;
input  [11:0] weights_4_20_val5032;
input  [11:0] weights_4_21_val5064;
input  [11:0] weights_4_22_val5096;
input  [11:0] weights_4_23_val5128;
input  [11:0] weights_4_24_val5160;
input  [11:0] weights_4_25_val5192;
input  [11:0] weights_4_26_val5224;
input  [11:0] weights_4_27_val5256;
input  [11:0] weights_4_28_val5288;
input  [11:0] weights_4_29_val5320;
input  [11:0] weights_4_30_val5352;
input  [11:0] weights_4_31_val5384;
input  [11:0] weights_5_0_val5416;
input  [11:0] weights_5_1_val5448;
input  [11:0] weights_5_2_val5480;
input  [11:0] weights_5_3_val5513;
input  [11:0] weights_5_4_val5545;
input  [11:0] weights_5_5_val5577;
input  [11:0] weights_5_6_val5609;
input  [11:0] weights_5_7_val5641;
input  [11:0] weights_5_8_val5673;
input  [11:0] weights_5_9_val5705;
input  [11:0] weights_5_10_val5737;
input  [11:0] weights_5_11_val5769;
input  [11:0] weights_5_12_val5801;
input  [11:0] weights_5_13_val5833;
input  [11:0] weights_5_14_val5865;
input  [11:0] weights_5_15_val5897;
input  [11:0] weights_5_16_val5929;
input  [11:0] weights_5_17_val5961;
input  [11:0] weights_5_18_val5993;
input  [11:0] weights_5_19_val6025;
input  [11:0] weights_5_20_val6058;
input  [11:0] weights_5_21_val6090;
input  [11:0] weights_5_22_val6122;
input  [11:0] weights_5_23_val6154;
input  [11:0] weights_5_24_val6186;
input  [11:0] weights_5_25_val6218;
input  [11:0] weights_5_26_val6250;
input  [11:0] weights_5_27_val6282;
input  [11:0] weights_5_28_val6314;
input  [11:0] weights_5_29_val6346;
input  [11:0] weights_5_30_val6378;
input  [11:0] weights_5_31_val6410;
input  [11:0] weights_6_0_val6442;
input  [11:0] weights_6_1_val6474;
input  [11:0] weights_6_2_val6506;
input  [11:0] weights_6_3_val6538;
input  [11:0] weights_6_4_val6570;
input  [11:0] weights_6_5_val6603;
input  [11:0] weights_6_6_val6635;
input  [11:0] weights_6_7_val6667;
input  [11:0] weights_6_8_val6699;
input  [11:0] weights_6_9_val6731;
input  [11:0] weights_6_10_val6763;
input  [11:0] weights_6_11_val6795;
input  [11:0] weights_6_12_val6827;
input  [11:0] weights_6_13_val6859;
input  [11:0] weights_6_14_val6891;
input  [11:0] weights_6_15_val6923;
input  [11:0] weights_6_16_val6955;
input  [11:0] weights_6_17_val6987;
input  [11:0] weights_6_18_val7019;
input  [11:0] weights_6_19_val7051;
input  [11:0] weights_6_20_val7083;
input  [11:0] weights_6_21_val7115;
input  [11:0] weights_6_22_val7148;
input  [11:0] weights_6_23_val7180;
input  [11:0] weights_6_24_val7212;
input  [11:0] weights_6_25_val7244;
input  [11:0] weights_6_26_val7276;
input  [11:0] weights_6_27_val7308;
input  [11:0] weights_6_28_val7340;
input  [11:0] weights_6_29_val7372;
input  [11:0] weights_6_30_val7404;
input  [11:0] weights_6_31_val7436;
input  [11:0] weights_7_0_val7468;
input  [11:0] weights_7_1_val7500;
input  [11:0] weights_7_2_val7532;
input  [11:0] weights_7_3_val7564;
input  [11:0] weights_7_4_val7596;
input  [11:0] weights_7_5_val7628;
input  [11:0] weights_7_6_val7660;
input  [11:0] weights_7_7_val7693;
input  [11:0] weights_7_8_val7725;
input  [11:0] weights_7_9_val7757;
input  [11:0] weights_7_10_val7789;
input  [11:0] weights_7_11_val7821;
input  [11:0] weights_7_12_val7853;
input  [11:0] weights_7_13_val7885;
input  [11:0] weights_7_14_val7917;
input  [11:0] weights_7_15_val7949;
input  [11:0] weights_7_16_val7981;
input  [11:0] weights_7_17_val8013;
input  [11:0] weights_7_18_val8045;
input  [11:0] weights_7_19_val8077;
input  [11:0] weights_7_20_val8109;
input  [11:0] weights_7_21_val8141;
input  [11:0] weights_7_22_val8173;
input  [11:0] weights_7_23_val8205;
input  [11:0] weights_7_24_val8238;
input  [11:0] weights_7_25_val8270;
input  [11:0] weights_7_26_val8302;
input  [11:0] weights_7_27_val8334;
input  [11:0] weights_7_28_val8366;
input  [11:0] weights_7_29_val8398;
input  [11:0] weights_7_30_val8430;
input  [11:0] weights_7_31_val8462;
input  [11:0] weights_8_0_val8494;
input  [11:0] weights_8_1_val8526;
input  [11:0] weights_8_2_val8558;
input  [11:0] weights_8_3_val8590;
input  [11:0] weights_8_4_val8622;
input  [11:0] weights_8_5_val8654;
input  [11:0] weights_8_6_val8686;
input  [11:0] weights_8_7_val8718;
input  [11:0] weights_8_8_val8750;
input  [11:0] weights_8_9_val8783;
input  [11:0] weights_8_10_val8815;
input  [11:0] weights_8_11_val8847;
input  [11:0] weights_8_12_val8879;
input  [11:0] weights_8_13_val8911;
input  [11:0] weights_8_14_val8943;
input  [11:0] weights_8_15_val8975;
input  [11:0] weights_8_16_val9007;
input  [11:0] weights_8_17_val9039;
input  [11:0] weights_8_18_val9071;
input  [11:0] weights_8_19_val9103;
input  [11:0] weights_8_20_val9135;
input  [11:0] weights_8_21_val9167;
input  [11:0] weights_8_22_val9199;
input  [11:0] weights_8_23_val9231;
input  [11:0] weights_8_24_val9263;
input  [11:0] weights_8_25_val9295;
input  [11:0] weights_8_26_val9327;
input  [11:0] weights_8_27_val9359;
input  [11:0] weights_8_28_val9391;
input  [11:0] weights_8_29_val9423;
input  [11:0] weights_8_30_val9455;
input  [11:0] weights_8_31_val9487;
input  [11:0] weights_9_0_val9519;
input  [11:0] weights_9_1_val9551;
input  [11:0] weights_9_2_val9583;
input  [11:0] weights_9_3_val9615;
input  [11:0] weights_9_4_val9647;
input  [11:0] weights_9_5_val9679;
input  [11:0] weights_9_6_val9711;
input  [11:0] weights_9_7_val9743;
input  [11:0] weights_9_8_val9775;
input  [11:0] weights_9_9_val9807;
input  [11:0] weights_9_10_val9839;
input  [11:0] weights_9_11_val9871;
input  [11:0] weights_9_12_val9903;
input  [11:0] weights_9_13_val9935;
input  [11:0] weights_9_14_val9967;
input  [11:0] weights_9_15_val9999;
input  [11:0] weights_9_16_val10031;
input  [11:0] weights_9_17_val10063;
input  [11:0] weights_9_18_val10095;
input  [11:0] weights_9_19_val10127;
input  [11:0] weights_9_20_val10159;
input  [11:0] weights_9_21_val10191;
input  [11:0] weights_9_22_val10223;
input  [11:0] weights_9_23_val10255;
input  [11:0] weights_9_24_val10287;
input  [11:0] weights_9_25_val10319;
input  [11:0] weights_9_26_val10351;
input  [11:0] weights_9_27_val10383;
input  [11:0] weights_9_28_val10415;
input  [11:0] weights_9_29_val10447;
input  [11:0] weights_9_30_val10479;
input  [11:0] weights_9_31_val10511;
input  [11:0] weights_10_0_val10543;
input  [11:0] weights_10_1_val10575;
input  [11:0] weights_10_2_val10607;
input  [11:0] weights_10_3_val10639;
input  [11:0] weights_10_4_val10671;
input  [11:0] weights_10_5_val10703;
input  [11:0] weights_10_6_val10735;
input  [11:0] weights_10_7_val10767;
input  [11:0] weights_10_8_val10799;
input  [11:0] weights_10_9_val10831;
input  [11:0] weights_10_10_val10863;
input  [11:0] weights_10_11_val10895;
input  [11:0] weights_10_12_val10927;
input  [11:0] weights_10_13_val10959;
input  [11:0] weights_10_14_val10991;
input  [11:0] weights_10_15_val11023;
input  [11:0] weights_10_16_val11055;
input  [11:0] weights_10_17_val11087;
input  [11:0] weights_10_18_val11119;
input  [11:0] weights_10_19_val11151;
input  [11:0] weights_10_20_val11183;
input  [11:0] weights_10_21_val11215;
input  [11:0] weights_10_22_val11247;
input  [11:0] weights_10_23_val11279;
input  [11:0] weights_10_24_val11311;
input  [11:0] weights_10_25_val11343;
input  [11:0] weights_10_26_val11375;
input  [11:0] weights_10_27_val11407;
input  [11:0] weights_10_28_val11439;
input  [11:0] weights_10_29_val11471;
input  [11:0] weights_10_30_val11503;
input  [11:0] weights_10_31_val11535;
input  [11:0] weights_11_0_val11567;
input  [11:0] weights_11_1_val11599;
input  [11:0] weights_11_2_val11631;
input  [11:0] weights_11_3_val11663;
input  [11:0] weights_11_4_val11695;
input  [11:0] weights_11_5_val11727;
input  [11:0] weights_11_6_val11759;
input  [11:0] weights_11_7_val11791;
input  [11:0] weights_11_8_val11823;
input  [11:0] weights_11_9_val11855;
input  [11:0] weights_11_10_val11887;
input  [11:0] weights_11_11_val11919;
input  [11:0] weights_11_12_val11951;
input  [11:0] weights_11_13_val11983;
input  [11:0] weights_11_14_val12015;
input  [11:0] weights_11_15_val12047;
input  [11:0] weights_11_16_val12079;
input  [11:0] weights_11_17_val12111;
input  [11:0] weights_11_18_val12143;
input  [11:0] weights_11_19_val12175;
input  [11:0] weights_11_20_val12207;
input  [11:0] weights_11_21_val12239;
input  [11:0] weights_11_22_val12271;
input  [11:0] weights_11_23_val12303;
input  [11:0] weights_11_24_val12335;
input  [11:0] weights_11_25_val12367;
input  [11:0] weights_11_26_val12399;
input  [11:0] weights_11_27_val12431;
input  [11:0] weights_11_28_val12463;
input  [11:0] weights_11_29_val12495;
input  [11:0] weights_11_30_val12527;
input  [11:0] weights_11_31_val12559;
input  [11:0] weights_12_0_val12591;
input  [11:0] weights_12_1_val12623;
input  [11:0] weights_12_2_val12655;
input  [11:0] weights_12_3_val12687;
input  [11:0] weights_12_4_val12719;
input  [11:0] weights_12_5_val12751;
input  [11:0] weights_12_6_val12783;
input  [11:0] weights_12_7_val12815;
input  [11:0] weights_12_8_val12847;
input  [11:0] weights_12_9_val12879;
input  [11:0] weights_12_10_val12911;
input  [11:0] weights_12_11_val12943;
input  [11:0] weights_12_12_val12975;
input  [11:0] weights_12_13_val13007;
input  [11:0] weights_12_14_val13039;
input  [11:0] weights_12_15_val13071;
input  [11:0] weights_12_16_val13103;
input  [11:0] weights_12_17_val13135;
input  [11:0] weights_12_18_val13167;
input  [11:0] weights_12_19_val13199;
input  [11:0] weights_12_20_val13231;
input  [11:0] weights_12_21_val13263;
input  [11:0] weights_12_22_val13295;
input  [11:0] weights_12_23_val13327;
input  [11:0] weights_12_24_val13359;
input  [11:0] weights_12_25_val13391;
input  [11:0] weights_12_26_val13423;
input  [11:0] weights_12_27_val13455;
input  [11:0] weights_12_28_val13487;
input  [11:0] weights_12_29_val13519;
input  [11:0] weights_12_30_val13551;
input  [11:0] weights_12_31_val13583;
input  [11:0] weights_13_0_val13615;
input  [11:0] weights_13_1_val13647;
input  [11:0] weights_13_2_val13679;
input  [11:0] weights_13_3_val13712;
input  [11:0] weights_13_4_val13744;
input  [11:0] weights_13_5_val13776;
input  [11:0] weights_13_6_val13808;
input  [11:0] weights_13_7_val13840;
input  [11:0] weights_13_8_val13872;
input  [11:0] weights_13_9_val13904;
input  [11:0] weights_13_10_val13936;
input  [11:0] weights_13_11_val13968;
input  [11:0] weights_13_12_val14000;
input  [11:0] weights_13_13_val14032;
input  [11:0] weights_13_14_val14064;
input  [11:0] weights_13_15_val14096;
input  [11:0] weights_13_16_val14128;
input  [11:0] weights_13_17_val14160;
input  [11:0] weights_13_18_val14192;
input  [11:0] weights_13_19_val14224;
input  [11:0] weights_13_20_val14257;
input  [11:0] weights_13_21_val14289;
input  [11:0] weights_13_22_val14321;
input  [11:0] weights_13_23_val14353;
input  [11:0] weights_13_24_val14385;
input  [11:0] weights_13_25_val14417;
input  [11:0] weights_13_26_val14449;
input  [11:0] weights_13_27_val14481;
input  [11:0] weights_13_28_val14513;
input  [11:0] weights_13_29_val14545;
input  [11:0] weights_13_30_val14577;
input  [11:0] weights_13_31_val14609;
input  [11:0] weights_14_0_val14641;
input  [11:0] weights_14_1_val14673;
input  [11:0] weights_14_2_val14705;
input  [11:0] weights_14_3_val14737;
input  [11:0] weights_14_4_val14769;
input  [11:0] weights_14_5_val14802;
input  [11:0] weights_14_6_val14834;
input  [11:0] weights_14_7_val14866;
input  [11:0] weights_14_8_val14898;
input  [11:0] weights_14_9_val14930;
input  [11:0] weights_14_10_val14962;
input  [11:0] weights_14_11_val14994;
input  [11:0] weights_14_12_val15026;
input  [11:0] weights_14_13_val15058;
input  [11:0] weights_14_14_val15090;
input  [11:0] weights_14_15_val15122;
input  [11:0] weights_14_16_val15154;
input  [11:0] weights_14_17_val15186;
input  [11:0] weights_14_18_val15218;
input  [11:0] weights_14_19_val15250;
input  [11:0] weights_14_20_val15282;
input  [11:0] weights_14_21_val15314;
input  [11:0] weights_14_22_val15346;
input  [11:0] weights_14_23_val15378;
input  [11:0] weights_14_24_val15410;
input  [11:0] weights_14_25_val15442;
input  [11:0] weights_14_26_val15474;
input  [11:0] weights_14_27_val15506;
input  [11:0] weights_14_28_val15538;
input  [11:0] weights_14_29_val15570;
input  [11:0] weights_14_30_val15602;
input  [11:0] weights_14_31_val15634;
input  [11:0] weights_15_0_val15666;
input  [11:0] weights_15_1_val15698;
input  [11:0] weights_15_2_val15730;
input  [11:0] weights_15_3_val15762;
input  [11:0] weights_15_4_val15794;
input  [11:0] weights_15_5_val15826;
input  [11:0] weights_15_6_val15858;
input  [11:0] weights_15_7_val15890;
input  [11:0] weights_15_8_val15922;
input  [11:0] weights_15_9_val15954;
input  [11:0] weights_15_10_val15986;
input  [11:0] weights_15_11_val16018;
input  [11:0] weights_15_12_val16050;
input  [11:0] weights_15_13_val16082;
input  [11:0] weights_15_14_val16114;
input  [11:0] weights_15_15_val16146;
input  [11:0] weights_15_16_val16178;
input  [11:0] weights_15_17_val16210;
input  [11:0] weights_15_18_val16242;
input  [11:0] weights_15_19_val16274;
input  [11:0] weights_15_20_val16306;
input  [11:0] weights_15_21_val16338;
input  [11:0] weights_15_22_val16370;
input  [11:0] weights_15_23_val16402;
input  [11:0] weights_15_24_val16434;
input  [11:0] weights_15_25_val16466;
input  [11:0] weights_15_26_val16498;
input  [11:0] weights_15_27_val16530;
input  [11:0] weights_15_28_val16562;
input  [11:0] weights_15_29_val16594;
input  [11:0] weights_15_30_val16626;
input  [11:0] weights_15_31_val16658;
input  [11:0] input_0_val32;
input  [11:0] input_1_val64;
input  [11:0] input_2_val96;
input  [11:0] input_3_val128;
input  [11:0] input_4_val160;
input  [11:0] input_5_val192;
input  [11:0] input_6_val224;
input  [11:0] input_7_val256;
input  [11:0] hidden_state_0_read;
input  [11:0] hidden_state_1_read;
input  [11:0] hidden_state_2_read;
input  [11:0] hidden_state_3_read;
input  [11:0] hidden_state_4_read;
input  [11:0] hidden_state_5_read;
input  [11:0] hidden_state_6_read;
input  [11:0] hidden_state_7_read;
output  [11:0] output_vectors_0_0_out;
output   output_vectors_0_0_out_ap_vld;
output  [11:0] output_vectors_1_0_out;
output   output_vectors_1_0_out_ap_vld;
output  [11:0] output_vectors_2_0_out;
output   output_vectors_2_0_out_ap_vld;
output  [11:0] output_vectors_3_0_out;
output   output_vectors_3_0_out_ap_vld;

reg ap_idle;
reg output_vectors_0_0_out_ap_vld;
reg output_vectors_1_0_out_ap_vld;
reg output_vectors_2_0_out_ap_vld;
reg output_vectors_3_0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln96_fu_5437_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    grp_dot_product_8ul_8ul_1_fu_4348_ap_ready;
wire   [4:0] grp_dot_product_8ul_8ul_1_fu_4348_col_val;
wire   [11:0] grp_dot_product_8ul_8ul_1_fu_4348_ap_return;
wire   [1:0] trunc_ln96_fu_5449_p1;
reg   [2:0] j_fu_1108;
wire   [2:0] add_ln96_fu_5443_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_9;
reg   [11:0] output_vectors_3_0_fu_1112;
reg   [11:0] output_vectors_2_0_fu_1116;
reg   [11:0] output_vectors_1_0_fu_1120;
reg   [11:0] output_vectors_0_0_fu_1124;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

network_top_dot_product_8ul_8ul_1 grp_dot_product_8ul_8ul_1_fu_4348(
    .ap_ready(grp_dot_product_8ul_8ul_1_fu_4348_ap_ready),
    .A_0_0_val(weights_0_0_val288),
    .A_0_1_val(weights_0_1_val320),
    .A_0_2_val(weights_0_2_val352),
    .A_0_3_val(weights_0_3_val384),
    .A_0_4_val(weights_0_4_val416),
    .A_0_5_val(weights_0_5_val448),
    .A_0_6_val(weights_0_6_val480),
    .A_0_7_val(weights_0_7_val512),
    .A_0_8_val(weights_0_8_val544),
    .A_0_9_val(weights_0_9_val577),
    .A_0_10_val(weights_0_10_val609),
    .A_0_11_val(weights_0_11_val641),
    .A_0_12_val(weights_0_12_val673),
    .A_0_13_val(weights_0_13_val705),
    .A_0_14_val(weights_0_14_val737),
    .A_0_15_val(weights_0_15_val769),
    .A_0_16_val(weights_0_16_val801),
    .A_0_17_val(weights_0_17_val833),
    .A_0_18_val(weights_0_18_val865),
    .A_0_19_val(weights_0_19_val897),
    .A_0_20_val(weights_0_20_val929),
    .A_0_21_val(weights_0_21_val961),
    .A_0_22_val(weights_0_22_val993),
    .A_0_23_val(weights_0_23_val1025),
    .A_0_24_val(weights_0_24_val1057),
    .A_0_25_val(weights_0_25_val1089),
    .A_0_26_val(weights_0_26_val1121),
    .A_0_27_val(weights_0_27_val1153),
    .A_0_28_val(weights_0_28_val1185),
    .A_0_29_val(weights_0_29_val1217),
    .A_0_30_val(weights_0_30_val1249),
    .A_0_31_val(weights_0_31_val1281),
    .A_1_0_val(weights_1_0_val1313),
    .A_1_1_val(weights_1_1_val1345),
    .A_1_2_val(weights_1_2_val1377),
    .A_1_3_val(weights_1_3_val1409),
    .A_1_4_val(weights_1_4_val1441),
    .A_1_5_val(weights_1_5_val1473),
    .A_1_6_val(weights_1_6_val1505),
    .A_1_7_val(weights_1_7_val1537),
    .A_1_8_val(weights_1_8_val1569),
    .A_1_9_val(weights_1_9_val1601),
    .A_1_10_val(weights_1_10_val1633),
    .A_1_11_val(weights_1_11_val1665),
    .A_1_12_val(weights_1_12_val1698),
    .A_1_13_val(weights_1_13_val1730),
    .A_1_14_val(weights_1_14_val1762),
    .A_1_15_val(weights_1_15_val1794),
    .A_1_16_val(weights_1_16_val1826),
    .A_1_17_val(weights_1_17_val1858),
    .A_1_18_val(weights_1_18_val1890),
    .A_1_19_val(weights_1_19_val1922),
    .A_1_20_val(weights_1_20_val1954),
    .A_1_21_val(weights_1_21_val1986),
    .A_1_22_val(weights_1_22_val2018),
    .A_1_23_val(weights_1_23_val2050),
    .A_1_24_val(weights_1_24_val2082),
    .A_1_25_val(weights_1_25_val2114),
    .A_1_26_val(weights_1_26_val2146),
    .A_1_27_val(weights_1_27_val2178),
    .A_1_28_val(weights_1_28_val2210),
    .A_1_29_val(weights_1_29_val2243),
    .A_1_30_val(weights_1_30_val2275),
    .A_1_31_val(weights_1_31_val2307),
    .A_2_0_val(weights_2_0_val2339),
    .A_2_1_val(weights_2_1_val2371),
    .A_2_2_val(weights_2_2_val2403),
    .A_2_3_val(weights_2_3_val2435),
    .A_2_4_val(weights_2_4_val2467),
    .A_2_5_val(weights_2_5_val2499),
    .A_2_6_val(weights_2_6_val2531),
    .A_2_7_val(weights_2_7_val2563),
    .A_2_8_val(weights_2_8_val2595),
    .A_2_9_val(weights_2_9_val2627),
    .A_2_10_val(weights_2_10_val2659),
    .A_2_11_val(weights_2_11_val2691),
    .A_2_12_val(weights_2_12_val2723),
    .A_2_13_val(weights_2_13_val2755),
    .A_2_14_val(weights_2_14_val2788),
    .A_2_15_val(weights_2_15_val2820),
    .A_2_16_val(weights_2_16_val2852),
    .A_2_17_val(weights_2_17_val2884),
    .A_2_18_val(weights_2_18_val2916),
    .A_2_19_val(weights_2_19_val2948),
    .A_2_20_val(weights_2_20_val2980),
    .A_2_21_val(weights_2_21_val3012),
    .A_2_22_val(weights_2_22_val3044),
    .A_2_23_val(weights_2_23_val3076),
    .A_2_24_val(weights_2_24_val3108),
    .A_2_25_val(weights_2_25_val3140),
    .A_2_26_val(weights_2_26_val3172),
    .A_2_27_val(weights_2_27_val3204),
    .A_2_28_val(weights_2_28_val3236),
    .A_2_29_val(weights_2_29_val3268),
    .A_2_30_val(weights_2_30_val3300),
    .A_2_31_val(weights_2_31_val3333),
    .A_3_0_val(weights_3_0_val3365),
    .A_3_1_val(weights_3_1_val3397),
    .A_3_2_val(weights_3_2_val3429),
    .A_3_3_val(weights_3_3_val3461),
    .A_3_4_val(weights_3_4_val3493),
    .A_3_5_val(weights_3_5_val3525),
    .A_3_6_val(weights_3_6_val3557),
    .A_3_7_val(weights_3_7_val3589),
    .A_3_8_val(weights_3_8_val3621),
    .A_3_9_val(weights_3_9_val3653),
    .A_3_10_val(weights_3_10_val3685),
    .A_3_11_val(weights_3_11_val3717),
    .A_3_12_val(weights_3_12_val3749),
    .A_3_13_val(weights_3_13_val3781),
    .A_3_14_val(weights_3_14_val3813),
    .A_3_15_val(weights_3_15_val3845),
    .A_3_16_val(weights_3_16_val3878),
    .A_3_17_val(weights_3_17_val3910),
    .A_3_18_val(weights_3_18_val3942),
    .A_3_19_val(weights_3_19_val3974),
    .A_3_20_val(weights_3_20_val4006),
    .A_3_21_val(weights_3_21_val4038),
    .A_3_22_val(weights_3_22_val4070),
    .A_3_23_val(weights_3_23_val4102),
    .A_3_24_val(weights_3_24_val4134),
    .A_3_25_val(weights_3_25_val4166),
    .A_3_26_val(weights_3_26_val4198),
    .A_3_27_val(weights_3_27_val4230),
    .A_3_28_val(weights_3_28_val4262),
    .A_3_29_val(weights_3_29_val4294),
    .A_3_30_val(weights_3_30_val4326),
    .A_3_31_val(weights_3_31_val4358),
    .A_4_0_val(weights_4_0_val4390),
    .A_4_1_val(weights_4_1_val4423),
    .A_4_2_val(weights_4_2_val4455),
    .A_4_3_val(weights_4_3_val4487),
    .A_4_4_val(weights_4_4_val4519),
    .A_4_5_val(weights_4_5_val4551),
    .A_4_6_val(weights_4_6_val4583),
    .A_4_7_val(weights_4_7_val4615),
    .A_4_8_val(weights_4_8_val4647),
    .A_4_9_val(weights_4_9_val4679),
    .A_4_10_val(weights_4_10_val4711),
    .A_4_11_val(weights_4_11_val4743),
    .A_4_12_val(weights_4_12_val4775),
    .A_4_13_val(weights_4_13_val4807),
    .A_4_14_val(weights_4_14_val4839),
    .A_4_15_val(weights_4_15_val4871),
    .A_4_16_val(weights_4_16_val4903),
    .A_4_17_val(weights_4_17_val4935),
    .A_4_18_val(weights_4_18_val4968),
    .A_4_19_val(weights_4_19_val5000),
    .A_4_20_val(weights_4_20_val5032),
    .A_4_21_val(weights_4_21_val5064),
    .A_4_22_val(weights_4_22_val5096),
    .A_4_23_val(weights_4_23_val5128),
    .A_4_24_val(weights_4_24_val5160),
    .A_4_25_val(weights_4_25_val5192),
    .A_4_26_val(weights_4_26_val5224),
    .A_4_27_val(weights_4_27_val5256),
    .A_4_28_val(weights_4_28_val5288),
    .A_4_29_val(weights_4_29_val5320),
    .A_4_30_val(weights_4_30_val5352),
    .A_4_31_val(weights_4_31_val5384),
    .A_5_0_val(weights_5_0_val5416),
    .A_5_1_val(weights_5_1_val5448),
    .A_5_2_val(weights_5_2_val5480),
    .A_5_3_val(weights_5_3_val5513),
    .A_5_4_val(weights_5_4_val5545),
    .A_5_5_val(weights_5_5_val5577),
    .A_5_6_val(weights_5_6_val5609),
    .A_5_7_val(weights_5_7_val5641),
    .A_5_8_val(weights_5_8_val5673),
    .A_5_9_val(weights_5_9_val5705),
    .A_5_10_val(weights_5_10_val5737),
    .A_5_11_val(weights_5_11_val5769),
    .A_5_12_val(weights_5_12_val5801),
    .A_5_13_val(weights_5_13_val5833),
    .A_5_14_val(weights_5_14_val5865),
    .A_5_15_val(weights_5_15_val5897),
    .A_5_16_val(weights_5_16_val5929),
    .A_5_17_val(weights_5_17_val5961),
    .A_5_18_val(weights_5_18_val5993),
    .A_5_19_val(weights_5_19_val6025),
    .A_5_20_val(weights_5_20_val6058),
    .A_5_21_val(weights_5_21_val6090),
    .A_5_22_val(weights_5_22_val6122),
    .A_5_23_val(weights_5_23_val6154),
    .A_5_24_val(weights_5_24_val6186),
    .A_5_25_val(weights_5_25_val6218),
    .A_5_26_val(weights_5_26_val6250),
    .A_5_27_val(weights_5_27_val6282),
    .A_5_28_val(weights_5_28_val6314),
    .A_5_29_val(weights_5_29_val6346),
    .A_5_30_val(weights_5_30_val6378),
    .A_5_31_val(weights_5_31_val6410),
    .A_6_0_val(weights_6_0_val6442),
    .A_6_1_val(weights_6_1_val6474),
    .A_6_2_val(weights_6_2_val6506),
    .A_6_3_val(weights_6_3_val6538),
    .A_6_4_val(weights_6_4_val6570),
    .A_6_5_val(weights_6_5_val6603),
    .A_6_6_val(weights_6_6_val6635),
    .A_6_7_val(weights_6_7_val6667),
    .A_6_8_val(weights_6_8_val6699),
    .A_6_9_val(weights_6_9_val6731),
    .A_6_10_val(weights_6_10_val6763),
    .A_6_11_val(weights_6_11_val6795),
    .A_6_12_val(weights_6_12_val6827),
    .A_6_13_val(weights_6_13_val6859),
    .A_6_14_val(weights_6_14_val6891),
    .A_6_15_val(weights_6_15_val6923),
    .A_6_16_val(weights_6_16_val6955),
    .A_6_17_val(weights_6_17_val6987),
    .A_6_18_val(weights_6_18_val7019),
    .A_6_19_val(weights_6_19_val7051),
    .A_6_20_val(weights_6_20_val7083),
    .A_6_21_val(weights_6_21_val7115),
    .A_6_22_val(weights_6_22_val7148),
    .A_6_23_val(weights_6_23_val7180),
    .A_6_24_val(weights_6_24_val7212),
    .A_6_25_val(weights_6_25_val7244),
    .A_6_26_val(weights_6_26_val7276),
    .A_6_27_val(weights_6_27_val7308),
    .A_6_28_val(weights_6_28_val7340),
    .A_6_29_val(weights_6_29_val7372),
    .A_6_30_val(weights_6_30_val7404),
    .A_6_31_val(weights_6_31_val7436),
    .A_7_0_val(weights_7_0_val7468),
    .A_7_1_val(weights_7_1_val7500),
    .A_7_2_val(weights_7_2_val7532),
    .A_7_3_val(weights_7_3_val7564),
    .A_7_4_val(weights_7_4_val7596),
    .A_7_5_val(weights_7_5_val7628),
    .A_7_6_val(weights_7_6_val7660),
    .A_7_7_val(weights_7_7_val7693),
    .A_7_8_val(weights_7_8_val7725),
    .A_7_9_val(weights_7_9_val7757),
    .A_7_10_val(weights_7_10_val7789),
    .A_7_11_val(weights_7_11_val7821),
    .A_7_12_val(weights_7_12_val7853),
    .A_7_13_val(weights_7_13_val7885),
    .A_7_14_val(weights_7_14_val7917),
    .A_7_15_val(weights_7_15_val7949),
    .A_7_16_val(weights_7_16_val7981),
    .A_7_17_val(weights_7_17_val8013),
    .A_7_18_val(weights_7_18_val8045),
    .A_7_19_val(weights_7_19_val8077),
    .A_7_20_val(weights_7_20_val8109),
    .A_7_21_val(weights_7_21_val8141),
    .A_7_22_val(weights_7_22_val8173),
    .A_7_23_val(weights_7_23_val8205),
    .A_7_24_val(weights_7_24_val8238),
    .A_7_25_val(weights_7_25_val8270),
    .A_7_26_val(weights_7_26_val8302),
    .A_7_27_val(weights_7_27_val8334),
    .A_7_28_val(weights_7_28_val8366),
    .A_7_29_val(weights_7_29_val8398),
    .A_7_30_val(weights_7_30_val8430),
    .A_7_31_val(weights_7_31_val8462),
    .A_8_0_val(weights_8_0_val8494),
    .A_8_1_val(weights_8_1_val8526),
    .A_8_2_val(weights_8_2_val8558),
    .A_8_3_val(weights_8_3_val8590),
    .A_8_4_val(weights_8_4_val8622),
    .A_8_5_val(weights_8_5_val8654),
    .A_8_6_val(weights_8_6_val8686),
    .A_8_7_val(weights_8_7_val8718),
    .A_8_8_val(weights_8_8_val8750),
    .A_8_9_val(weights_8_9_val8783),
    .A_8_10_val(weights_8_10_val8815),
    .A_8_11_val(weights_8_11_val8847),
    .A_8_12_val(weights_8_12_val8879),
    .A_8_13_val(weights_8_13_val8911),
    .A_8_14_val(weights_8_14_val8943),
    .A_8_15_val(weights_8_15_val8975),
    .A_8_16_val(weights_8_16_val9007),
    .A_8_17_val(weights_8_17_val9039),
    .A_8_18_val(weights_8_18_val9071),
    .A_8_19_val(weights_8_19_val9103),
    .A_8_20_val(weights_8_20_val9135),
    .A_8_21_val(weights_8_21_val9167),
    .A_8_22_val(weights_8_22_val9199),
    .A_8_23_val(weights_8_23_val9231),
    .A_8_24_val(weights_8_24_val9263),
    .A_8_25_val(weights_8_25_val9295),
    .A_8_26_val(weights_8_26_val9327),
    .A_8_27_val(weights_8_27_val9359),
    .A_8_28_val(weights_8_28_val9391),
    .A_8_29_val(weights_8_29_val9423),
    .A_8_30_val(weights_8_30_val9455),
    .A_8_31_val(weights_8_31_val9487),
    .A_9_0_val(weights_9_0_val9519),
    .A_9_1_val(weights_9_1_val9551),
    .A_9_2_val(weights_9_2_val9583),
    .A_9_3_val(weights_9_3_val9615),
    .A_9_4_val(weights_9_4_val9647),
    .A_9_5_val(weights_9_5_val9679),
    .A_9_6_val(weights_9_6_val9711),
    .A_9_7_val(weights_9_7_val9743),
    .A_9_8_val(weights_9_8_val9775),
    .A_9_9_val(weights_9_9_val9807),
    .A_9_10_val(weights_9_10_val9839),
    .A_9_11_val(weights_9_11_val9871),
    .A_9_12_val(weights_9_12_val9903),
    .A_9_13_val(weights_9_13_val9935),
    .A_9_14_val(weights_9_14_val9967),
    .A_9_15_val(weights_9_15_val9999),
    .A_9_16_val(weights_9_16_val10031),
    .A_9_17_val(weights_9_17_val10063),
    .A_9_18_val(weights_9_18_val10095),
    .A_9_19_val(weights_9_19_val10127),
    .A_9_20_val(weights_9_20_val10159),
    .A_9_21_val(weights_9_21_val10191),
    .A_9_22_val(weights_9_22_val10223),
    .A_9_23_val(weights_9_23_val10255),
    .A_9_24_val(weights_9_24_val10287),
    .A_9_25_val(weights_9_25_val10319),
    .A_9_26_val(weights_9_26_val10351),
    .A_9_27_val(weights_9_27_val10383),
    .A_9_28_val(weights_9_28_val10415),
    .A_9_29_val(weights_9_29_val10447),
    .A_9_30_val(weights_9_30_val10479),
    .A_9_31_val(weights_9_31_val10511),
    .A_10_0_val(weights_10_0_val10543),
    .A_10_1_val(weights_10_1_val10575),
    .A_10_2_val(weights_10_2_val10607),
    .A_10_3_val(weights_10_3_val10639),
    .A_10_4_val(weights_10_4_val10671),
    .A_10_5_val(weights_10_5_val10703),
    .A_10_6_val(weights_10_6_val10735),
    .A_10_7_val(weights_10_7_val10767),
    .A_10_8_val(weights_10_8_val10799),
    .A_10_9_val(weights_10_9_val10831),
    .A_10_10_val(weights_10_10_val10863),
    .A_10_11_val(weights_10_11_val10895),
    .A_10_12_val(weights_10_12_val10927),
    .A_10_13_val(weights_10_13_val10959),
    .A_10_14_val(weights_10_14_val10991),
    .A_10_15_val(weights_10_15_val11023),
    .A_10_16_val(weights_10_16_val11055),
    .A_10_17_val(weights_10_17_val11087),
    .A_10_18_val(weights_10_18_val11119),
    .A_10_19_val(weights_10_19_val11151),
    .A_10_20_val(weights_10_20_val11183),
    .A_10_21_val(weights_10_21_val11215),
    .A_10_22_val(weights_10_22_val11247),
    .A_10_23_val(weights_10_23_val11279),
    .A_10_24_val(weights_10_24_val11311),
    .A_10_25_val(weights_10_25_val11343),
    .A_10_26_val(weights_10_26_val11375),
    .A_10_27_val(weights_10_27_val11407),
    .A_10_28_val(weights_10_28_val11439),
    .A_10_29_val(weights_10_29_val11471),
    .A_10_30_val(weights_10_30_val11503),
    .A_10_31_val(weights_10_31_val11535),
    .A_11_0_val(weights_11_0_val11567),
    .A_11_1_val(weights_11_1_val11599),
    .A_11_2_val(weights_11_2_val11631),
    .A_11_3_val(weights_11_3_val11663),
    .A_11_4_val(weights_11_4_val11695),
    .A_11_5_val(weights_11_5_val11727),
    .A_11_6_val(weights_11_6_val11759),
    .A_11_7_val(weights_11_7_val11791),
    .A_11_8_val(weights_11_8_val11823),
    .A_11_9_val(weights_11_9_val11855),
    .A_11_10_val(weights_11_10_val11887),
    .A_11_11_val(weights_11_11_val11919),
    .A_11_12_val(weights_11_12_val11951),
    .A_11_13_val(weights_11_13_val11983),
    .A_11_14_val(weights_11_14_val12015),
    .A_11_15_val(weights_11_15_val12047),
    .A_11_16_val(weights_11_16_val12079),
    .A_11_17_val(weights_11_17_val12111),
    .A_11_18_val(weights_11_18_val12143),
    .A_11_19_val(weights_11_19_val12175),
    .A_11_20_val(weights_11_20_val12207),
    .A_11_21_val(weights_11_21_val12239),
    .A_11_22_val(weights_11_22_val12271),
    .A_11_23_val(weights_11_23_val12303),
    .A_11_24_val(weights_11_24_val12335),
    .A_11_25_val(weights_11_25_val12367),
    .A_11_26_val(weights_11_26_val12399),
    .A_11_27_val(weights_11_27_val12431),
    .A_11_28_val(weights_11_28_val12463),
    .A_11_29_val(weights_11_29_val12495),
    .A_11_30_val(weights_11_30_val12527),
    .A_11_31_val(weights_11_31_val12559),
    .A_12_0_val(weights_12_0_val12591),
    .A_12_1_val(weights_12_1_val12623),
    .A_12_2_val(weights_12_2_val12655),
    .A_12_3_val(weights_12_3_val12687),
    .A_12_4_val(weights_12_4_val12719),
    .A_12_5_val(weights_12_5_val12751),
    .A_12_6_val(weights_12_6_val12783),
    .A_12_7_val(weights_12_7_val12815),
    .A_12_8_val(weights_12_8_val12847),
    .A_12_9_val(weights_12_9_val12879),
    .A_12_10_val(weights_12_10_val12911),
    .A_12_11_val(weights_12_11_val12943),
    .A_12_12_val(weights_12_12_val12975),
    .A_12_13_val(weights_12_13_val13007),
    .A_12_14_val(weights_12_14_val13039),
    .A_12_15_val(weights_12_15_val13071),
    .A_12_16_val(weights_12_16_val13103),
    .A_12_17_val(weights_12_17_val13135),
    .A_12_18_val(weights_12_18_val13167),
    .A_12_19_val(weights_12_19_val13199),
    .A_12_20_val(weights_12_20_val13231),
    .A_12_21_val(weights_12_21_val13263),
    .A_12_22_val(weights_12_22_val13295),
    .A_12_23_val(weights_12_23_val13327),
    .A_12_24_val(weights_12_24_val13359),
    .A_12_25_val(weights_12_25_val13391),
    .A_12_26_val(weights_12_26_val13423),
    .A_12_27_val(weights_12_27_val13455),
    .A_12_28_val(weights_12_28_val13487),
    .A_12_29_val(weights_12_29_val13519),
    .A_12_30_val(weights_12_30_val13551),
    .A_12_31_val(weights_12_31_val13583),
    .A_13_0_val(weights_13_0_val13615),
    .A_13_1_val(weights_13_1_val13647),
    .A_13_2_val(weights_13_2_val13679),
    .A_13_3_val(weights_13_3_val13712),
    .A_13_4_val(weights_13_4_val13744),
    .A_13_5_val(weights_13_5_val13776),
    .A_13_6_val(weights_13_6_val13808),
    .A_13_7_val(weights_13_7_val13840),
    .A_13_8_val(weights_13_8_val13872),
    .A_13_9_val(weights_13_9_val13904),
    .A_13_10_val(weights_13_10_val13936),
    .A_13_11_val(weights_13_11_val13968),
    .A_13_12_val(weights_13_12_val14000),
    .A_13_13_val(weights_13_13_val14032),
    .A_13_14_val(weights_13_14_val14064),
    .A_13_15_val(weights_13_15_val14096),
    .A_13_16_val(weights_13_16_val14128),
    .A_13_17_val(weights_13_17_val14160),
    .A_13_18_val(weights_13_18_val14192),
    .A_13_19_val(weights_13_19_val14224),
    .A_13_20_val(weights_13_20_val14257),
    .A_13_21_val(weights_13_21_val14289),
    .A_13_22_val(weights_13_22_val14321),
    .A_13_23_val(weights_13_23_val14353),
    .A_13_24_val(weights_13_24_val14385),
    .A_13_25_val(weights_13_25_val14417),
    .A_13_26_val(weights_13_26_val14449),
    .A_13_27_val(weights_13_27_val14481),
    .A_13_28_val(weights_13_28_val14513),
    .A_13_29_val(weights_13_29_val14545),
    .A_13_30_val(weights_13_30_val14577),
    .A_13_31_val(weights_13_31_val14609),
    .A_14_0_val(weights_14_0_val14641),
    .A_14_1_val(weights_14_1_val14673),
    .A_14_2_val(weights_14_2_val14705),
    .A_14_3_val(weights_14_3_val14737),
    .A_14_4_val(weights_14_4_val14769),
    .A_14_5_val(weights_14_5_val14802),
    .A_14_6_val(weights_14_6_val14834),
    .A_14_7_val(weights_14_7_val14866),
    .A_14_8_val(weights_14_8_val14898),
    .A_14_9_val(weights_14_9_val14930),
    .A_14_10_val(weights_14_10_val14962),
    .A_14_11_val(weights_14_11_val14994),
    .A_14_12_val(weights_14_12_val15026),
    .A_14_13_val(weights_14_13_val15058),
    .A_14_14_val(weights_14_14_val15090),
    .A_14_15_val(weights_14_15_val15122),
    .A_14_16_val(weights_14_16_val15154),
    .A_14_17_val(weights_14_17_val15186),
    .A_14_18_val(weights_14_18_val15218),
    .A_14_19_val(weights_14_19_val15250),
    .A_14_20_val(weights_14_20_val15282),
    .A_14_21_val(weights_14_21_val15314),
    .A_14_22_val(weights_14_22_val15346),
    .A_14_23_val(weights_14_23_val15378),
    .A_14_24_val(weights_14_24_val15410),
    .A_14_25_val(weights_14_25_val15442),
    .A_14_26_val(weights_14_26_val15474),
    .A_14_27_val(weights_14_27_val15506),
    .A_14_28_val(weights_14_28_val15538),
    .A_14_29_val(weights_14_29_val15570),
    .A_14_30_val(weights_14_30_val15602),
    .A_14_31_val(weights_14_31_val15634),
    .A_15_0_val(weights_15_0_val15666),
    .A_15_1_val(weights_15_1_val15698),
    .A_15_2_val(weights_15_2_val15730),
    .A_15_3_val(weights_15_3_val15762),
    .A_15_4_val(weights_15_4_val15794),
    .A_15_5_val(weights_15_5_val15826),
    .A_15_6_val(weights_15_6_val15858),
    .A_15_7_val(weights_15_7_val15890),
    .A_15_8_val(weights_15_8_val15922),
    .A_15_9_val(weights_15_9_val15954),
    .A_15_10_val(weights_15_10_val15986),
    .A_15_11_val(weights_15_11_val16018),
    .A_15_12_val(weights_15_12_val16050),
    .A_15_13_val(weights_15_13_val16082),
    .A_15_14_val(weights_15_14_val16114),
    .A_15_15_val(weights_15_15_val16146),
    .A_15_16_val(weights_15_16_val16178),
    .A_15_17_val(weights_15_17_val16210),
    .A_15_18_val(weights_15_18_val16242),
    .A_15_19_val(weights_15_19_val16274),
    .A_15_20_val(weights_15_20_val16306),
    .A_15_21_val(weights_15_21_val16338),
    .A_15_22_val(weights_15_22_val16370),
    .A_15_23_val(weights_15_23_val16402),
    .A_15_24_val(weights_15_24_val16434),
    .A_15_25_val(weights_15_25_val16466),
    .A_15_26_val(weights_15_26_val16498),
    .A_15_27_val(weights_15_27_val16530),
    .A_15_28_val(weights_15_28_val16562),
    .A_15_29_val(weights_15_29_val16594),
    .A_15_30_val(weights_15_30_val16626),
    .A_15_31_val(weights_15_31_val16658),
    .col_val(grp_dot_product_8ul_8ul_1_fu_4348_col_val),
    .B_1_0_val(input_0_val32),
    .B_1_1_val(input_1_val64),
    .B_1_2_val(input_2_val96),
    .B_1_3_val(input_3_val128),
    .B_1_4_val(input_4_val160),
    .B_1_5_val(input_5_val192),
    .B_1_6_val(input_6_val224),
    .B_1_7_val(input_7_val256),
    .B_2_0_val(hidden_state_0_read),
    .B_2_1_val(hidden_state_1_read),
    .B_2_2_val(hidden_state_2_read),
    .B_2_3_val(hidden_state_3_read),
    .B_2_4_val(hidden_state_4_read),
    .B_2_5_val(hidden_state_5_read),
    .B_2_6_val(hidden_state_6_read),
    .B_2_7_val(hidden_state_7_read),
    .ap_return(grp_dot_product_8ul_8ul_1_fu_4348_ap_return)
);

network_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln96_fu_5437_p2 == 1'd0)) begin
            j_fu_1108 <= add_ln96_fu_5443_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_1108 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((icmp_ln96_fu_5437_p2 == 1'd0) & (trunc_ln96_fu_5449_p1 == 2'd0))) begin
            output_vectors_0_0_fu_1124 <= grp_dot_product_8ul_8ul_1_fu_4348_ap_return;
        end else if ((ap_loop_init == 1'b1)) begin
            output_vectors_0_0_fu_1124 <= p_read16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((icmp_ln96_fu_5437_p2 == 1'd0) & (trunc_ln96_fu_5449_p1 == 2'd1))) begin
            output_vectors_1_0_fu_1120 <= grp_dot_product_8ul_8ul_1_fu_4348_ap_return;
        end else if ((ap_loop_init == 1'b1)) begin
            output_vectors_1_0_fu_1120 <= p_read17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((icmp_ln96_fu_5437_p2 == 1'd0) & (trunc_ln96_fu_5449_p1 == 2'd2))) begin
            output_vectors_2_0_fu_1116 <= grp_dot_product_8ul_8ul_1_fu_4348_ap_return;
        end else if ((ap_loop_init == 1'b1)) begin
            output_vectors_2_0_fu_1116 <= p_read18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((icmp_ln96_fu_5437_p2 == 1'd0) & (trunc_ln96_fu_5449_p1 == 2'd3))) begin
            output_vectors_3_0_fu_1112 <= grp_dot_product_8ul_8ul_1_fu_4348_ap_return;
        end else if ((ap_loop_init == 1'b1)) begin
            output_vectors_3_0_fu_1112 <= p_read19;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_5437_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_9 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_9 = j_fu_1108;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_5437_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        output_vectors_0_0_out_ap_vld = 1'b1;
    end else begin
        output_vectors_0_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_5437_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        output_vectors_1_0_out_ap_vld = 1'b1;
    end else begin
        output_vectors_1_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_5437_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        output_vectors_2_0_out_ap_vld = 1'b1;
    end else begin
        output_vectors_2_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_5437_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        output_vectors_3_0_out_ap_vld = 1'b1;
    end else begin
        output_vectors_3_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln96_fu_5443_p2 = (ap_sig_allocacmp_j_9 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_dot_product_8ul_8ul_1_fu_4348_col_val = trunc_ln96_fu_5449_p1;

assign icmp_ln96_fu_5437_p2 = ((ap_sig_allocacmp_j_9 == 3'd4) ? 1'b1 : 1'b0);

assign output_vectors_0_0_out = output_vectors_0_0_fu_1124;

assign output_vectors_1_0_out = output_vectors_1_0_fu_1120;

assign output_vectors_2_0_out = output_vectors_2_0_fu_1116;

assign output_vectors_3_0_out = output_vectors_3_0_fu_1112;

assign trunc_ln96_fu_5449_p1 = ap_sig_allocacmp_j_9[1:0];

endmodule //network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_1
