// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module network_top_network_top_Pipeline_load_weight1_matrix_inner_loop13 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356_ap_vld,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357,
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19_ap_vld,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18,
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356_ap_vld;
output  [17:0] p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357;
output   p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19_ap_vld;
output  [17:0] network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18;
output   network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18_ap_vld;

reg ap_idle;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356_ap_vld;
reg p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19_ap_vld;
reg network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln193_fu_352_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] c_load_fu_349_p1;
reg   [6:0] c_13_fu_340;
wire   [6:0] add_ln193_fu_358_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_c;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

network_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln193_fu_352_p2 == 1'd0)) begin
            c_13_fu_340 <= add_ln193_fu_358_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_13_fu_340 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_c = 7'd0;
    end else begin
        ap_sig_allocacmp_c = c_13_fu_340;
    end
end

always @ (*) begin
    if ((~(c_load_fu_349_p1 == 7'd78) & ~(c_load_fu_349_p1 == 7'd77) & ~(c_load_fu_349_p1 == 7'd76) & ~(c_load_fu_349_p1 == 7'd75) & ~(c_load_fu_349_p1 == 7'd74) & ~(c_load_fu_349_p1 == 7'd73) & ~(c_load_fu_349_p1 == 7'd72) & ~(c_load_fu_349_p1 == 7'd71) & ~(c_load_fu_349_p1 == 7'd70) & ~(c_load_fu_349_p1 == 7'd69) & ~(c_load_fu_349_p1 == 7'd68) & ~(c_load_fu_349_p1 == 7'd67) & ~(c_load_fu_349_p1 == 7'd66) & ~(c_load_fu_349_p1 == 7'd65) & ~(c_load_fu_349_p1 == 7'd64) & ~(c_load_fu_349_p1 == 7'd63) & ~(c_load_fu_349_p1 == 7'd62) & ~(c_load_fu_349_p1 == 7'd61) & ~(c_load_fu_349_p1 == 7'd60) & ~(c_load_fu_349_p1 == 7'd59) & ~(c_load_fu_349_p1 == 7'd58) & ~(c_load_fu_349_p1 == 7'd57) & ~(c_load_fu_349_p1 == 7'd56) & ~(c_load_fu_349_p1 == 7'd55) & ~(c_load_fu_349_p1 == 7'd54) & ~(c_load_fu_349_p1 == 7'd53) & ~(c_load_fu_349_p1 == 7'd52) & ~(c_load_fu_349_p1 == 7'd51) & ~(c_load_fu_349_p1 == 7'd50) & ~(c_load_fu_349_p1 == 7'd49) & ~(c_load_fu_349_p1 == 7'd48) & ~(c_load_fu_349_p1 == 7'd47) & ~(c_load_fu_349_p1 == 7'd46) & ~(c_load_fu_349_p1 
    == 7'd45) & ~(c_load_fu_349_p1 == 7'd44) & ~(c_load_fu_349_p1 == 7'd43) & ~(c_load_fu_349_p1 == 7'd42) & ~(c_load_fu_349_p1 == 7'd41) & ~(c_load_fu_349_p1 == 7'd40) & ~(c_load_fu_349_p1 == 7'd39) & ~(c_load_fu_349_p1 == 7'd38) & ~(c_load_fu_349_p1 == 7'd37) & ~(c_load_fu_349_p1 == 7'd36) & ~(c_load_fu_349_p1 == 7'd35) & ~(c_load_fu_349_p1 == 7'd34) & ~(c_load_fu_349_p1 == 7'd33) & ~(c_load_fu_349_p1 == 7'd32) & ~(c_load_fu_349_p1 == 7'd31) & ~(c_load_fu_349_p1 == 7'd30) & ~(c_load_fu_349_p1 == 7'd29) & ~(c_load_fu_349_p1 == 7'd28) & ~(c_load_fu_349_p1 == 7'd27) & ~(c_load_fu_349_p1 == 7'd26) & ~(c_load_fu_349_p1 == 7'd25) & ~(c_load_fu_349_p1 == 7'd24) & ~(c_load_fu_349_p1 == 7'd23) & ~(c_load_fu_349_p1 == 7'd22) & ~(c_load_fu_349_p1 == 7'd21) & ~(c_load_fu_349_p1 == 7'd20) & ~(c_load_fu_349_p1 == 7'd19) & ~(c_load_fu_349_p1 == 7'd18) & ~(c_load_fu_349_p1 == 7'd17) & ~(c_load_fu_349_p1 == 7'd16) & ~(c_load_fu_349_p1 == 7'd15) & ~(c_load_fu_349_p1 == 7'd14) & ~(c_load_fu_349_p1 == 7'd13) & ~(c_load_fu_349_p1 == 
    7'd12) & ~(c_load_fu_349_p1 == 7'd11) & ~(c_load_fu_349_p1 == 7'd10) & ~(c_load_fu_349_p1 == 7'd9) & ~(c_load_fu_349_p1 == 7'd8) & ~(c_load_fu_349_p1 == 7'd7) & ~(c_load_fu_349_p1 == 7'd6) & ~(c_load_fu_349_p1 == 7'd5) & ~(c_load_fu_349_p1 == 7'd4) & ~(c_load_fu_349_p1 == 7'd3) & ~(c_load_fu_349_p1 == 7'd2) & ~(c_load_fu_349_p1 == 7'd1) & ~(c_load_fu_349_p1 == 7'd0) & (ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd78))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd77))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd76))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd75))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd74))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd73))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd72))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd71))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd70))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd69))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd68))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd67))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd66))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd65))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd64))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd63))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd62))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd61))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd60))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd59))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd58))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd57))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd56))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd55))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd54))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd53))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd52))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd51))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd50))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd49))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd48))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd47))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd46))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd45))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd44))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd43))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd42))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd41))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd40))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd39))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd38))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd37))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd36))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd35))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd34))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd33))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd32))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd31))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd30))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd29))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd28))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd27))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd26))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd25))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd24))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd23))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd22))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd21))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd20))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd10))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd11))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd12))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd13))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd14))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd15))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd16))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd17))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd18))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd19))) begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22_ap_vld = 1'b1;
    end else begin
        network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd0))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd1))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd2))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd3))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd4))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd5))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd6))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd7))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd8))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln193_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (c_load_fu_349_p1 == 7'd9))) begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357_ap_vld = 1'b1;
    end else begin
        p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln193_fu_358_p2 = (ap_sig_allocacmp_c + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign c_load_fu_349_p1 = ap_sig_allocacmp_c;

assign icmp_ln193_fu_352_p2 = ((ap_sig_allocacmp_c == 7'd80) ? 1'b1 : 1'b0);

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_18 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_19 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_20 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_22 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_23 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_24 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_25 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_26 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_27 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_28 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_29 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_30 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_31 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_33 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_34 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_35 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_36 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_37 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_38 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_39 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_40 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_41 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_42 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_44 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_45 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_46 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_47 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_48 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_49 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_50 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_51 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_52 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_53 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_55 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_56 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_57 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_58 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_59 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_60 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_61 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_62 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_63 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_64 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_66 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_67 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_68 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_69 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_70 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_71 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_72 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_73 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_74 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_75 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_77 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_78 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_79 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_80 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_81 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_82 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_32_weights1_83 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_13 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_14 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_15 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_16 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_17 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_18 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_19 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_20 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_21 = 18'd131072;

assign network_top_params_struct_ap_ufixed_ap_ufixed_ap_int_ap_int_weights1_22 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10348 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10349 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10350 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10351 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10352 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10353 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10354 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10355 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10356 = 18'd131072;

assign p_ZZ11network_topP13params_structP9ap_ufixedILi22ELi5EL9ap_q_mode0EL9ap_o_mode0EL_10357 = 18'd131072;

endmodule //network_top_network_top_Pipeline_load_weight1_matrix_inner_loop13
