set SynModuleInfo {
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop
    SUBMODULES {
      {MODELNAME network_top_flow_control_loop_pipe_sequential_init RTLNAME network_top_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME network_top_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop1 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop1 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop1}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop2 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop2 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop2}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop3 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop3 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop3}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop4 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop4 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop4}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop5 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop5 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop5}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop6 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop6 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop6}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop7 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop7 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop7}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop8 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop8 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop8}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop9 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop9 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop9}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop10 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop10 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop10}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop11 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop11 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop11}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop12 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop12 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop12}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop13 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop13 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop13}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop14 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop14 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop14}
  {SRCNAME network_top_Pipeline_load_weight1_matrix_inner_loop15 MODELNAME network_top_Pipeline_load_weight1_matrix_inner_loop15 RTLNAME network_top_network_top_Pipeline_load_weight1_matrix_inner_loop15}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop16 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop16 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop16}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop17 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop17 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop17}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop18 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop18 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop18}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop19 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop19 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop19}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop20 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop20 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop20}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop21 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop21 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop21}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop22 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop22 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop22}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop23 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop23 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop23}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop24 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop24 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop24}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop25 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop25 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop25}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop26 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop26 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop26}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop27 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop27 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop27}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop28 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop28 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop28}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop29 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop29 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop29}
  {SRCNAME network_top_Pipeline_load_weight2_matrix_inner_loop30 MODELNAME network_top_Pipeline_load_weight2_matrix_inner_loop30 RTLNAME network_top_network_top_Pipeline_load_weight2_matrix_inner_loop30}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop31 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop31 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop31}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop32 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop32 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop32}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop33 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop33 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop33}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop34 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop34 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop34}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop35 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop35 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop35}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop36 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop36 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop36}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop37 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop37 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop37}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop38 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop38 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop38}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop39 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop39 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop39}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop40 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop40 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop40}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop41 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop41 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop41}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop42 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop42 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop42}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop43 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop43 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop43}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop44 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop44 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop44}
  {SRCNAME network_top_Pipeline_load_weight3_matrix_inner_loop45 MODELNAME network_top_Pipeline_load_weight3_matrix_inner_loop45 RTLNAME network_top_network_top_Pipeline_load_weight3_matrix_inner_loop45}
  {SRCNAME network_top_Pipeline_load_biases3_matrix MODELNAME network_top_Pipeline_load_biases3_matrix RTLNAME network_top_network_top_Pipeline_load_biases3_matrix}
  {SRCNAME {dot_product<8ul, 8ul>} MODELNAME dot_product_8ul_8ul_s RTLNAME network_top_dot_product_8ul_8ul_s
    SUBMODULES {
      {MODELNAME network_top_mux_32_5_12_1_1 RTLNAME network_top_mux_32_5_12_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME network_top_mul_12s_12s_24_1_1 RTLNAME network_top_mul_12s_12s_24_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_1} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_1 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_1}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_153} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_153 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_153}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_154} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_154 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_154}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_155} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_155 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_155}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_156} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_156 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_156}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_157} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_157 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_157}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_158} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_158 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_158}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>_Pipeline_OUTTER_LOOP_159} MODELNAME LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_159 RTLNAME network_top_LSTM_8ul_8ul_8ul_Pipeline_OUTTER_LOOP_159}
  {SRCNAME sigm MODELNAME sigm RTLNAME network_top_sigm}
  {SRCNAME hyper_tan MODELNAME hyper_tan RTLNAME network_top_hyper_tan}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>} MODELNAME LSTM_8ul_8ul_8ul_s RTLNAME network_top_LSTM_8ul_8ul_8ul_s
    SUBMODULES {
      {MODELNAME network_top_mul_12s_12s_22_1_1 RTLNAME network_top_mul_12s_12s_22_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME network_top_mac_muladd_12s_12s_22s_22_4_1 RTLNAME network_top_mac_muladd_12s_12s_22s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME {dot_product<8ul, 8ul>.1} MODELNAME dot_product_8ul_8ul_1 RTLNAME network_top_dot_product_8ul_8ul_1}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_1} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_1 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_1}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_146} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_146 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_146}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_147} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_147 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_147}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_148} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_148 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_148}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_149} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_149 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_149}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_150} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_150 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_150}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_151} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_151 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_151}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2_Pipeline_OUTTER_LOOP_152} MODELNAME LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_152 RTLNAME network_top_LSTM_8ul_8ul_8ul_2_Pipeline_OUTTER_LOOP_152}
  {SRCNAME {LSTM<8ul, 8ul, 8ul>.2} MODELNAME LSTM_8ul_8ul_8ul_2 RTLNAME network_top_LSTM_8ul_8ul_8ul_2}
  {SRCNAME network_top MODELNAME network_top RTLNAME network_top IS_TOP 1
    SUBMODULES {
      {MODELNAME network_top_gmem_m_axi RTLNAME network_top_gmem_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME network_top_control_s_axi RTLNAME network_top_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
